"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { academyApi } from "@/lib/api";

type Academy = { id: string };
type Intelligence = { activeEnrolments: number; attendanceRisk: { studentId: string; records: number; attendanceRate: number }[]; occupancy: { id: string; name: string; activeEnrolments: number; waitlisted: number; capacity: number; pressure: number }[]; collections: { invoiceNumber: string; totalAmount: number; dueDate: string; daysOverdue: number }[]; workload: { teacherId: string; teacherName: string; scheduledHours: number; sessions: number }[] };
const money = (amount: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(amount);

export default function Intelligence() {
  const [data, setData] = useState<Intelligence>(); const [message, setMessage] = useState("Loading operational intelligence…");
  useEffect(() => { void (async () => { try { const academyResponse = await academyApi("/api/academies"); if (!academyResponse.ok) throw Error(); const academies: Academy[] = await academyResponse.json(); if (!academies[0]) throw Error(); const response = await academyApi(`/api/academies/${academies[0].id}/admin-intelligence`); if (!response.ok) throw Error(); setData(await response.json()); setMessage(""); } catch { setMessage("Operational intelligence could not be loaded."); } })(); }, []);
  const capacityAlerts = data?.occupancy.filter(item => item.pressure >= 90).length ?? 0;
  return <main className="enterprise-settings intelligence-standard"><header className="intelligence-heading"><span className="intelligence-title-icon" aria-hidden="true">◈</span><div><p>Administration</p><h1>Admin intelligence</h1></div></header>{message && <p className="intelligence-notice" role="status">{message}</p>}{data && <><section className="intelligence-kpis"><article><span>Active enrolments</span><b>{data.activeEnrolments}</b><small>Students currently enrolled in delivery.</small></article><article><span>Attendance risks</span><b>{data.attendanceRisk.length}</b><small>Learners needing attendance attention.</small></article><article><span>Capacity alerts</span><b>{capacityAlerts}</b><small>Batches at or above 90% capacity.</small></article><article><span>Overdue invoices</span><b>{data.collections.length}</b><small>Collections requiring follow-up.</small></article></section><section className="intelligence-layout"><Panel eyebrow="Intervention queue" title="Attendance intervention"><ul>{data.attendanceRisk.length ? data.attendanceRisk.map(item => <li key={item.studentId}><div><b>{item.attendanceRate}% attendance</b><small>{item.records} attendance records</small></div><Link href={`/student-profile?id=${item.studentId}`}>View student <span aria-hidden="true">→</span></Link></li>) : <Empty text="No attendance-risk learners." />}</ul></Panel><Panel eyebrow="Capacity" title="Batch capacity pressure"><ul>{data.occupancy.length ? data.occupancy.map(item => <li key={item.id}><div><b>{item.name}</b><small>{item.activeEnrolments} active / {item.capacity} capacity{item.waitlisted ? ` · ${item.waitlisted} waitlisted` : ""}</small></div><strong data-risk={item.pressure >= 90}>{item.pressure}%</strong></li>) : <Empty text="No batch-capacity information is available." />}</ul></Panel><Panel eyebrow="Collections" title="Collections ageing"><ul>{data.collections.length ? data.collections.map(item => <li key={item.invoiceNumber}><div><b>{item.invoiceNumber}</b><small>{money(item.totalAmount)} · due {item.dueDate}</small></div><strong data-risk="true">{item.daysOverdue} days</strong></li>) : <Empty text="No overdue invoices." />}</ul></Panel><Panel eyebrow="Delivery" title="Teacher workload"><ul>{data.workload.length ? data.workload.map(item => <li key={item.teacherId}><div><b>{item.teacherName || `Teacher ${item.teacherId.slice(0, 8)}`}</b><small>Scheduled delivery load</small></div><strong>{item.scheduledHours} hrs<small>{item.sessions} sessions</small></strong></li>) : <Empty text="No teacher workload is available." />}</ul></Panel></section></>}</main>;
}
function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="intelligence-panel"><header><p>{eyebrow}</p><h2>{title}</h2></header>{children}</section>; }
function Empty({ text }: { text: string }) { return <p className="intelligence-empty">{text}</p>; }
