"use client";

import { FormEvent, useEffect, useState } from "react";
import { academyApi, apiHeaders } from "@/lib/api";

type Academy = { id: string };
type Campaign = { id: string; name: string; channel: string; startDate: string; endDate?: string | null; budget: number; status: string };
const statuses = ["Draft", "Active", "Paused", "Completed"];

export default function SalesCampaignsPage() {
  const [academy, setAcademy] = useState<Academy>();
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [message, setMessage] = useState("Loading campaigns…");
  const [name, setName] = useState(""); const [channel, setChannel] = useState("WhatsApp");
  const [startDate, setStartDate] = useState(new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Kolkata" }));
  const [budget, setBudget] = useState(""); const [status, setStatus] = useState("Draft");
  async function load(academyId?: string) { const id = academyId ?? academy?.id; if (!id) return; const response = await academyApi(`/api/academies/${id}/sales-marketing/campaigns`, { cache: "no-store" }); if (!response.ok) throw new Error(); setCampaigns(await response.json()); setMessage(""); }
  useEffect(() => { void (async () => { try { const response = await academyApi("/api/academies", { cache: "no-store" }); const academies: Academy[] = await response.json(); if (!response.ok || !academies[0]) throw new Error(); setAcademy(academies[0]); await load(academies[0].id); } catch { setMessage("Campaigns could not be loaded. Please sign in and restart the API if needed."); } })(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!academy) return; const response = await academyApi(`/api/academies/${academy.id}/sales-marketing/campaigns`, { method: "POST", headers: apiHeaders(true), body: JSON.stringify({ name, channel, startDate, budget: Number(budget || 0), status }) }); if (!response.ok) return setMessage("Enter a campaign name and valid budget."); setName(""); setBudget(""); await load(); }
  async function update(campaign: Campaign, nextStatus: string) { if (!academy) return; const response = await academyApi(`/api/academies/${academy.id}/sales-marketing/campaigns/${campaign.id}`, { method: "PATCH", headers: apiHeaders(true), body: JSON.stringify({ status: nextStatus, budget: campaign.budget, endDate: campaign.endDate || null }) }); if (!response.ok) return setMessage("Campaign status could not be updated."); await load(); }
  return <main className="enterprise-settings"><header className="enterprise-page-header"><p>Sales & Marketing</p><h2>Campaigns</h2></header><p className="enterprise-page-intro">Plan, launch and track each outreach campaign in one place.</p>{message && <p className="mt-5 text-sm text-amber-500">{message}</p>}<section className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={create} className="surface-panel rounded-xl p-5"><h3 className="font-semibold">Create campaign</h3><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Campaign name" className="mt-4 w-full" /><div className="mt-3 grid gap-3 sm:grid-cols-2"><select value={channel} onChange={(event) => setChannel(event.target.value)}><option>WhatsApp</option><option>Instagram</option><option>Website</option><option>Email</option><option>Referral</option><option>Other</option></select><input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><input type="number" min="0" step="0.01" value={budget} onChange={(event) => setBudget(event.target.value)} placeholder="Budget (₹)" /><select value={status} onChange={(event) => setStatus(event.target.value)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></div><button className="primary-action mt-5" disabled={!academy}>Create campaign</button></form><section className="space-y-3">{campaigns.length === 0 ? <div className="surface-panel rounded-xl p-5 text-sm text-slate-500">No campaigns yet.</div> : campaigns.map((campaign) => <article key={campaign.id} className="surface-panel flex flex-wrap items-center justify-between gap-4 rounded-xl p-5"><div><h3 className="font-semibold">{campaign.name}</h3><p className="mt-1 text-sm text-slate-500">{campaign.channel} · Starts {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeZone: "Asia/Kolkata" }).format(new Date(`${campaign.startDate}T00:00:00+05:30`))} · ₹{campaign.budget.toLocaleString("en-IN")}</p></div><select value={campaign.status} onChange={(event) => void update(campaign, event.target.value)} className="min-w-32">{statuses.map((item) => <option key={item}>{item}</option>)}</select></article>)}</section></section></main>;
}
