"use client";

import { useEffect, useState } from "react";
import { academyApi, apiHeaders } from "@/lib/api";

type Academy = { id: string }; type Guardian = { id: string; firstName: string; lastName: string };
type Profile = { preferredName?: string; addressLine1?: string; city?: string; state?: string; postalCode?: string; preferredLanguage?: string; students?: unknown[]; invoices?: unknown[]; communications?: unknown[] };
const count = (rows?: unknown[]) => rows?.length ?? 0;

export default function GuardianProfilePage() {
  const [academy, setAcademy] = useState<Academy>(); const [guardians, setGuardians] = useState<Guardian[]>([]); const [guardianId, setGuardianId] = useState(""); const [profile, setProfile] = useState<Profile>(); const [form, setForm] = useState<Record<string, string>>({}); const [message, setMessage] = useState("Loading family records…"); const [saving, setSaving] = useState(false);
  function prepare(value: Profile) { setForm({ preferredName: value.preferredName ?? "", addressLine1: value.addressLine1 ?? "", city: value.city ?? "", state: value.state ?? "", postalCode: value.postalCode ?? "", preferredLanguage: value.preferredLanguage ?? "" }); }
  async function load(id: string, academyId = academy?.id) { if (!academyId || !id) return; const response = await academyApi(`/api/academies/${academyId}/guardians/${id}/profile`); if (!response.ok) throw new Error(); const value: Profile = await response.json(); setProfile(value); prepare(value); }
  useEffect(() => { void (async () => { try { const academies: Academy[] = await (await academyApi("/api/academies")).json(); if (!academies[0]) return setMessage("Create an academy before managing family records."); setAcademy(academies[0]); const rows: Guardian[] = await (await academyApi(`/api/academies/${academies[0].id}/guardians`)).json(); setGuardians(rows); if (rows[0]) { setGuardianId(rows[0].id); await load(rows[0].id, academies[0].id); } setMessage(""); } catch { setMessage("Guardian records could not be loaded."); } })(); }, []);
  async function select(id: string) { setGuardianId(id); try { await load(id); setMessage(""); } catch { setMessage("The guardian record could not be loaded."); } }
  async function save() { if (!academy || !guardianId) return; setSaving(true); try { const response = await academyApi(`/api/academies/${academy.id}/guardians/${guardianId}/profile`, { method: "PUT", headers: apiHeaders(true), body: JSON.stringify(form) }); const value = await response.json().catch(() => null); if (!response.ok) throw new Error(value?.message ?? "The profile could not be saved."); setProfile(value); prepare(value); setMessage("Guardian administrative profile saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "The profile could not be saved."); } finally { setSaving(false); } }
  const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <main className="enterprise-settings"><header className="enterprise-page-header"><p>Learners & families / record</p><h2>Guardian / Family 360</h2><span>A reusable family contact record with controlled relationship, communication and billing context.</span></header><section className="enterprise-settings-toolbar"><select value={guardianId} onChange={(e) => void select(e.target.value)} className="field max-w-md"><option value="">Select guardian</option>{guardians.map((guardian) => <option key={guardian.id} value={guardian.id}>{guardian.firstName} {guardian.lastName}</option>)}</select></section>{message && <p className="mt-5 rounded-lg border border-amber-700/50 bg-amber-950/30 p-3 text-sm text-amber-100">{message}</p>}{profile && <><section className="mt-5 grid gap-4 md:grid-cols-3"><div className="surface-panel rounded-xl p-5"><p className="text-sm text-slate-400">Linked learners</p><strong className="mt-2 block text-3xl">{count(profile.students)}</strong></div><div className="surface-panel rounded-xl p-5"><p className="text-sm text-slate-400">Family invoices</p><strong className="mt-2 block text-3xl">{count(profile.invoices)}</strong></div><div className="surface-panel rounded-xl p-5"><p className="text-sm text-slate-400">Communication history</p><strong className="mt-2 block text-3xl">{count(profile.communications)}</strong></div></section><section className="surface-panel mt-5 rounded-xl p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Administrative guardian profile</h3><p className="mt-1 text-sm text-slate-400">Contact preferences and address details shared safely across linked learners.</p></div><button onClick={() => void save()} disabled={saving} className="rounded-lg bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-60">{saving ? "Saving…" : "Save profile"}</button></div><div className="mt-5 grid gap-3 md:grid-cols-2"><input value={form.preferredName ?? ""} onChange={(e) => set("preferredName", e.target.value)} placeholder="Preferred name" className="field" /><input value={form.preferredLanguage ?? ""} onChange={(e) => set("preferredLanguage", e.target.value)} placeholder="Preferred language" className="field" /><input value={form.addressLine1 ?? ""} onChange={(e) => set("addressLine1", e.target.value)} placeholder="Address" className="field" /><input value={form.city ?? ""} onChange={(e) => set("city", e.target.value)} placeholder="City" className="field" /><input value={form.state ?? ""} onChange={(e) => set("state", e.target.value)} placeholder="State" className="field" /><input value={form.postalCode ?? ""} onChange={(e) => set("postalCode", e.target.value)} placeholder="Postal / PIN code" className="field" /></div></section></>}</main>;
}
