// Actual editor TSX, controlled hooks/transport. No live SQL/device acceptance.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const ts=require('../../apps/web/node_modules/typescript'),jsx=require('../../apps/web/node_modules/react/jsx-runtime');
const source=fs.readFileSync('apps/web/src/components/admission-fee-editor.tsx','utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
function nodes(n){return Array.isArray(n)?n.flatMap(nodes):!n||typeof n!=='object'?[]:[n,...nodes(n.props?.children)];}
const tick=()=>new Promise(r=>setImmediate(r));
async function fixture(config={}){
 let index=0,refIndex=0,effectIndex=0;const state=new Map(),refs=[],deps=[],effects=[],cleanups=[],calls=[],module={exports:{}};
 const react={useState:v=>{const k=index++;if(!state.has(k))state.set(k,v);return[state.get(k),v=>state.set(k,typeof v==='function'?v(state.get(k)):v)];},useRef:v=>{const k=refIndex++;return refs[k]??(refs[k]={current:v});},useEffect:(fn,next)=>{const k=effectIndex++;if(!deps[k]||next.some((v,i)=>v!==deps[k][i])){deps[k]=next;effects.push(fn);}}};
 const api=async(url,init={})=>{calls.push({url,...init});assert.equal(url,'/api/academies/owned/students/student/fee-arrangements/admission-fee');
  if(init.method){if(config.writeGate)await config.writeGate;if(config.network)throw Error('Synthetic network');return{ok:!config.status,status:config.status||200};}
  if(config.mountGate)await config.mountGate;
  return{ok:!config.initialFailure,json:async()=>config.details===undefined?{amount:1200.25,dueDate:'2026-11-01'}:config.details};
 };
 new Function('require','module','exports',code)(n=>n==='react/jsx-runtime'?jsx:n==='react'?react:n==='@/lib/api'?{academyApi:api,apiHeaders:()=>({})}:n==='@/components/design-system/controls'?{StandardDateField:'date'}:(()=>{throw Error(n)})(),module,module.exports);
 const wrapper=module.exports.AdmissionFeeEditor({academyId:'owned',studentId:'student'});
 const render=()=>{index=refIndex=effectIndex=0;return wrapper.type(wrapper.props);};
 async function settle(){for(let i=0;i<4;i++){for(const fn of effects.splice(0)){const cleanup=fn();if(cleanup)cleanups.push(cleanup);}await tick();render();}}
 render();await settle();
 const handler=()=>nodes(render()).find(n=>n.type==='form').props.onSubmit;
 return{state,calls,render,settle,wrapper,other:module.exports.AdmissionFeeEditor({academyId:'owned',studentId:'other'}),handler,action:()=>handler()({preventDefault(){}}),unmount:()=>cleanups.forEach(fn=>fn()),writes:()=>calls.filter(c=>c.method)};
}
test('Checked mount, durable accessible save, original PUT and retained values',async()=>{const p=await fixture();assert.equal(p.state.get(0),'1200.25');await p.action();await p.settle();assert.equal(p.state.get(2),'Admission fee saved.');assert.equal(p.state.get(0),'1200.25');assert.equal(p.state.get(1),'2026-11-01');assert.equal(p.state.get(4),false);assert.deepEqual(JSON.parse(p.writes()[0].body),{amount:1200.25,dueDate:'2026-11-01'});assert.equal(p.writes()[0].method,'PUT');assert.equal(p.calls[0].cache,'no-store');assert.equal(p.calls.length,2);const ns=nodes(p.render());assert.equal(ns.find(n=>n.props?.role==='status').props['aria-live'],'polite');const input=ns.find(n=>n.type==='input');assert.equal(input.props.min,'0');assert.equal(input.props.step,'0.01');assert.equal(input.props.required,undefined);});
for(const [amount,dueDate,expected]of[['','',{amount:null,dueDate:null}],['0','',{amount:0,dueDate:null}],['1.01','',{amount:1.01,dueDate:null}],['','2026-11-01',{amount:null,dueDate:'2026-11-01'}]])test('Unchanged optional/zero/date request '+JSON.stringify(expected),async()=>{const p=await fixture();p.state.set(0,amount);p.state.set(1,dueDate);await p.action();assert.deepEqual(JSON.parse(p.writes()[0].body),expected);});
for(const status of[400,403,500,503])test('HTTP '+status+' retained draft, no retry',async()=>{const p=await fixture({status});await p.action();assert.equal(p.state.get(0),'1200.25');assert.equal(p.state.get(1),'2026-11-01');assert.equal(p.state.get(4),false);assert.match(p.state.get(2),status>=500?/could not be confirmed.*before retrying/:/could not be saved.*retained/);assert.equal(p.calls.length,2);});
test('Network uncertainty releases guard and keeps values',async()=>{const p=await fixture({network:true});await p.action();assert.match(p.state.get(2),/could not be confirmed/);assert.equal(p.state.get(0),'1200.25');assert.equal(p.state.get(4),false);assert.equal(p.writes().length,1);});
for(const config of[{initialFailure:true},{details:null},{details:[]},{details:{amount:'1200'}},{details:{dueDate:123}}])test('Failed/malformed initial read prevents save '+JSON.stringify(config),async()=>{const p=await fixture(config);await p.action();assert.equal(p.writes().length,0);assert.equal(p.state.get(3),false);assert.match(p.state.get(2),/could not be loaded/);assert.equal(nodes(p.render()).find(n=>n.type==='fieldset').props.disabled,true);});
test('Null optional fields load as empty',async()=>{const p=await fixture({details:{amount:null,dueDate:null}});assert.equal(p.state.get(0),'');assert.equal(p.state.get(1),'');assert.equal(p.state.get(3),true);});
test('Synchronous same-tick stale submit and date change guarded',async()=>{let release;const gate=new Promise(r=>release=r),p=await fixture({writeGate:gate}),handler=p.handler(),date=nodes(p.render()).find(n=>n.type==='date').props.onChange;const first=handler({preventDefault(){}});const second=handler({preventDefault(){}});date('2026-12-31');try{assert.equal(p.writes().length,1);assert.equal(p.state.get(1),'2026-11-01');assert.equal(nodes(p.render()).find(n=>n.type==='fieldset').props.disabled,true);assert.equal(nodes(p.render()).find(n=>n.type==='button').props.disabled,true);}finally{release();}await Promise.all([first,second]);assert.equal(p.state.get(4),false);});
test('Student scope keyed to a fresh editor',async()=>{const p=await fixture();assert.notEqual(p.wrapper.key,p.other.key);assert.deepEqual(JSON.parse(p.wrapper.key),['owned','student']);});
for(const stage of['mount','write'])test('Unmount during '+stage+' ignores late values/status',async()=>{let release;const gate=new Promise(r=>release=r),p=await fixture(stage==='mount'?{mountGate:gate}:{writeGate:gate});let first;if(stage==='write')first=p.action();await tick();p.unmount();const snapshot=[...p.state];release();if(first)await first;await p.settle();assert.deepEqual([...p.state],snapshot);const before=p.writes().length;await p.action();assert.equal(p.writes().length,before);});
test('Rerender does not fetch again or erase success',async()=>{const p=await fixture();await p.settle();assert.equal(p.calls.length,1);await p.action();await p.settle();assert.equal(p.calls.length,2);assert.equal(p.state.get(2),'Admission fee saved.');});
