// Actual ResultRow handlers with controlled hooks; browser rendering is a separate gate.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const ts=require('../../apps/web/node_modules/typescript'),jsx=require('../../apps/web/node_modules/react/jsx-runtime');
const code=ts.transpileModule(fs.readFileSync('apps/web/src/app/assessments/page.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText+'\nmodule.exports.ResultRow = ResultRow;';
function row(result,saving=false){let index=0;const state=new Map(),calls=[],module={exports:{}};
 new Function('require','module','exports',code)(n=>n==='react/jsx-runtime'?jsx:n==='react'?{useState:v=>{const key=index++;return[state.has(key)?state.get(key):v,v=>state.set(key,v)];},useEffect:()=>{},useRef:v=>({current:v})}:n==='@/components/design-system/controls'?{StandardSelectField:'mode'}:n==='@/components/workspace-nav'?{WorkspaceNav:'nav'}:n==='@/lib/api'?{}:(()=>{throw Error(n)})(),module,module.exports);
 const render=()=>{index=0;return module.exports.ResultRow({student:{id:'s',firstName:'QA',lastName:'Learner'},result,maxScore:100,saving,onSave:async(...args)=>calls.push(args)});};
 const nodes=n=>Array.isArray(n)?n.flatMap(nodes):!n||typeof n!=='object'?[]:[n,...nodes(n.props?.children)];
 const find=label=>nodes(render()).find(n=>n.props?.['aria-label']===label),mode=()=>nodes(render()).find(n=>n.type==='mode'),save=()=>nodes(render()).find(n=>n.type==='button');return{find,mode,save,calls};}
test('Automatic result score edit retains automatic mode and sends explicit mode',()=>{const r=row({score:80,grade:'Pass',isGradeManual:false});r.find('Assessment score').props.onChange({target:{value:'20'}});assert.equal(r.mode().props.value,'automatic');assert.equal(r.find('Manual grade').props.disabled,true);r.save().props.onClick();assert.equal(r.calls[0][1],20);assert.equal(r.calls[0][4],false);});
test('Manual override survives score-only edit',()=>{const r=row({score:80,grade:'Merit',isGradeManual:true});r.find('Assessment score').props.onChange({target:{value:'0'}});assert.equal(r.mode().props.value,'manual');assert.equal(r.save().props.disabled,false);r.save().props.onClick();assert.equal(r.calls[0][2],'Merit');assert.equal(r.calls[0][4],true);});
test('Legacy grade is preserved until explicit automatic selection',()=>{const r=row({score:80,grade:'Pass'});assert.equal(r.mode().props.value,'manual');r.mode().props.onChange('automatic');r.save().props.onClick();assert.equal(r.calls[0][4],false);});
test('New result defaults to automatic and zero score is valid',()=>{const r=row();assert.equal(r.mode().props.value,'automatic');r.find('Assessment score').props.onChange({target:{value:'0'}});assert.equal(r.save().props.disabled,false);});
for(const value of ['', '-1','101','NaN'])test(`Invalid score ${value} blocks save`,()=>{const r=row();r.find('Assessment score').props.onChange({target:{value}});assert.equal(r.save().props.disabled,true);});
test('Manual empty grade blocks save',()=>{const r=row({score:50});r.mode().props.onChange('manual');assert.equal(r.save().props.disabled,true);});
test('Saving disables mode and grade controls',()=>{const r=row({score:80,grade:'Merit',isGradeManual:true},true);assert.equal(r.mode().props.disabled,true);assert.equal(r.find('Manual grade').props.disabled,true);assert.equal(r.save().props.disabled,true);});

function page({manual=false,failure,refreshFailure=false}={}){
 const result={studentId:'s',score:80,grade:'Pass',isGradeManual:manual},state=new Map(),calls=[];let index=0;
 const initial=[{id:'a'},[{id:'b',name:'QA batch'}],[{id:'s',firstName:'QA',lastName:'Learner'}],[{studentId:'s',batchId:'b',status:'Active'}],[{id:'x',batchId:'b',title:'QA',maxScore:100}],[],'x',[result]];
 const module={exports:{}};new Function('require','module','exports',code)(n=>n==='react/jsx-runtime'?jsx:n==='react'?{useState:v=>{const key=index++;return[state.has(key)?state.get(key):initial[key]??v,v=>state.set(key,v)];},useEffect:()=>{},useRef:v=>({current:v})}:n==='@/components/design-system/controls'?{StandardSelectField:'mode'}:n==='@/components/workspace-nav'?{WorkspaceNav:'nav'}:n==='@/lib/api'?{apiHeaders:()=>({}),academyApi:async(url,options={})=>{calls.push({url,...options});if(failure==='network'&&options.method)throw Error('Synthetic network');return{ok:options.method?!failure:!refreshFailure,json:async()=>options.method?{message:'Synthetic save rejected.'}:[result]};}}:(()=>{throw Error(n)})(),module,module.exports);
 const nodes=n=>Array.isArray(n)?n.flatMap(nodes):!n||typeof n!=='object'?[]:[n,...nodes(n.props?.children)];const tree=module.exports.default(),r=nodes(tree).find(n=>typeof n.type==='function'&&n.type.name==='ResultRow');assert.ok(r);return{save:()=>r.props.onSave('s',20,'Pass','Note',manual),calls,state};
}
for(const manual of [false,true])test(`Page save ${manual?'manual':'automatic'} sends explicit mode and confirmed notice`,async()=>{const p=page({manual});await p.save();const writes=p.calls.filter(x=>x.method);assert.equal(writes.length,1);const body=JSON.parse(writes[0].body);assert.equal(body.isGradeManual,manual);assert.equal(body.grade,manual?'Pass':null);assert.equal(body.score,20);assert.equal(p.state.get(15),'Assessment result saved.');assert.equal(p.state.get(16),'');});
test('Confirmed save with failed refresh keeps success notice',async()=>{const p=page({refreshFailure:true});await p.save();assert.match(p.state.get(15),/^Assessment result saved, but/);assert.equal(p.state.get(16),'');});
test('Rejected save shows server guidance and retains entries',async()=>{const p=page({failure:400});await p.save();assert.equal(p.state.get(15),'Synthetic save rejected.');assert.equal(p.calls.length,1);assert.equal(p.state.get(16),'');});
test('Unconfirmed network save retains entries and releases pending state',async()=>{const p=page({failure:'network'});await p.save();assert.match(p.state.get(15),/could not be confirmed/);assert.equal(p.state.get(16),'');});
