// Actual TSX handlers with synthetic hooks/transport; not SQL/authorization proof.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const ts=require('../../apps/web/node_modules/typescript'),jsx=require('../../apps/web/node_modules/react/jsx-runtime');
const source=process.env.QA_CAMPAIGNS_BASELINE==='1'?require('node:child_process').execFileSync('git',['show','HEAD:apps/web/src/app/sales-campaigns/page.tsx'],{encoding:'utf8'}):fs.readFileSync('apps/web/src/app/sales-campaigns/page.tsx','utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
function nodes(n){return Array.isArray(n)?n.flatMap(nodes):!n||typeof n!=='object'?[]:[n,...nodes(n.props?.children)];}
const tick=()=>new Promise(r=>setImmediate(r));
async function page(config={}){
 let index=0,ri=0,ei=0;const state=new Map(),refs=[],deps=[],effects=[],calls=[],module={exports:{}};
 const campaign={id:'campaign',name:'Synthetic campaign',channel:'Website',startDate:'2026-10-31',endDate:config.endDate?'2026-11-30':null,budget:100.25,status:'Draft'};
 const react={useState:v=>{const k=index++;if(!state.has(k))state.set(k,v);return[state.get(k),v=>state.set(k,typeof v==='function'?v(state.get(k)):v)];},useRef:v=>{const k=ri++;return refs[k]??(refs[k]={current:v});},useEffect:(fn,next)=>{const k=ei++;if(!deps[k]||next.some((v,i)=>v!==deps[k][i])){deps[k]=next;effects.push(fn);}}};
 const api=async(url,init={})=>{
  calls.push({url,...init});if(init.method){if(config.writeGate)await config.writeGate;if(config.network)throw Error('Synthetic network');return{ok:!config.status,status:config.status||200};}
  assert.equal(init.cache,'no-store');if(url==='/api/academies')return{ok:!config.academyStatus,status:config.academyStatus||200,json:async()=>config.noAcademy?[]:[{id:'owned'}]};
  assert.equal(url,'/api/academies/owned/sales-marketing/campaigns');if(calls.some(c=>c.method)){if(config.readGate)await config.readGate;if(config.refreshFailure)return{ok:false,status:503};}
  return{ok:!config.initialFailure,json:async()=>config.malformed?{}:[campaign]};
 };
 new Function('require','module','exports',code)(n=>n==='react/jsx-runtime'?jsx:n==='react'?react:n==='@/lib/api'?{academyApi:api,apiHeaders:()=>({})}:n==='@/components/workspace-nav'?{WorkspaceNav:'nav'}:n==='@/components/design-system/controls'?{StandardSelectField:'select',StandardDateField:'date'}:(()=>{throw Error(n)})(),module,module.exports);
 const render=()=>{index=ri=ei=0;return module.exports.default();};
 async function settle(){for(let i=0;i<5;i++){for(const fn of effects.splice(0))fn();await tick();render();}}
 render();await settle();for(const[k,v]of[[3,' Draft campaign '],[4,'Instagram'],[5,'2026-10-31'],[6,config.blank?'':'25.50'],[7,'Paused']])state.set(k,v);
 const handler=kind=>{const tree=nodes(render());if(kind==='create'){const h=tree.find(n=>n.type==='form').props.onSubmit;return()=>h({preventDefault(){}});}const h=tree.find(n=>n.props?.name==='campaign-status-campaign').props.onChange;return async()=>{h('Active');await settle();};};
 return{state,calls,campaign,render,settle,handler,writes:()=>calls.filter(c=>c.method),notice:()=>state.get(2)};
}
const success={create:'Campaign created.',update:'Synthetic campaign moved to Active.'};
for(const kind of['create','update']){
 test(kind+' durable polite success, exact payload, matching reset',async()=>{const p=await page();await p.handler(kind)();await p.settle();assert.equal(p.notice(),success[kind]);const w=p.writes()[0];assert.equal(w.url,'/api/academies/owned/sales-marketing/campaigns'+(kind==='create'?'':'/campaign'));assert.equal(w.method,kind==='create'?'POST':'PATCH');assert.deepEqual(JSON.parse(w.body),kind==='create'?{name:' Draft campaign ',channel:'Instagram',startDate:'2026-10-31',budget:25.5,status:'Paused'}:{status:'Active',budget:100.25,endDate:null});assert.equal(p.state.get(3),kind==='create'?'':' Draft campaign ');assert.equal(p.state.get(6),kind==='create'?'':'25.50');for(const[k,v]of[[4,'Instagram'],[5,'2026-10-31'],[7,'Paused'],[8,false]])assert.equal(p.state.get(k),v);assert.equal(nodes(p.render()).find(n=>n.props?.role==='status').props['aria-live'],'polite');});
 test(kind+' confirmed save survives failed readback',async()=>{const p=await page({refreshFailure:true});await p.handler(kind)();assert.ok(p.notice().startsWith(success[kind]));assert.match(p.notice(),/could not be refreshed; do not repeat/);assert.equal(p.state.get(3),kind==='create'?'':' Draft campaign ');assert.equal(p.writes().length,1);assert.equal(p.state.get(8),false);});
 for(const status of[400,403,500,503])test(kind+' HTTP '+status+' retains draft, no retry',async()=>{const p=await page({status});await p.handler(kind)();assert.match(p.notice(),status>=500?/could not be confirmed.*before retrying/:/could not/);assert.equal(p.state.get(3),' Draft campaign ');assert.equal(p.state.get(6),'25.50');assert.equal(p.calls.length,3);assert.equal(p.writes().length,1);assert.equal(p.state.get(8),false);});
 test(kind+' network uncertainty caught',async()=>{const p=await page({network:true});await p.handler(kind)();assert.match(p.notice(),/could not be confirmed.*retained.*before retrying/);assert.equal(p.state.get(3),' Draft campaign ');assert.equal(p.writes().length,1);assert.equal(p.state.get(8),false);});
 for(const stage of['write','readback'])test(kind+' '+stage+' guards duplicate/opposing stale handlers',async()=>{let release;const gate=new Promise(r=>release=r),p=await page(stage==='write'?{writeGate:gate}:{readGate:gate});p.state.set(2,'Old error');const h=p.handler(kind),other=p.handler(kind==='create'?'update':'create'),first=h();await tick();const all=Promise.allSettled([first,h(),other()]);try{assert.equal(p.writes().length,1);const tree=nodes(p.render());assert.ok(tree.find(n=>n.type==='fieldset')?.props.disabled);assert.ok(tree.filter(n=>n.type==='button'||n.type==='select').every(n=>n.props.disabled));assert.notEqual(p.notice(),'Old error');}finally{release();}for(const r of await all)if(r.status==='rejected')throw r.reason;await p.settle();assert.equal(p.writes().length,1);assert.equal(p.state.get(8),false);});
}
test('Blank optional budget remains zero',async()=>{const p=await page({blank:true});await p.handler('create')();assert.equal(JSON.parse(p.writes()[0].body).budget,0);});
test('Existing end date and budget remain unchanged in status request',async()=>{const p=await page({endDate:true});await p.handler('update')();assert.deepEqual(JSON.parse(p.writes()[0].body),{status:'Active',budget:100.25,endDate:'2026-11-30'});});
for(const config of[{noAcademy:true},{academyStatus:401},{academyStatus:403},{initialFailure:true},{malformed:true}])test('Unavailable workspace '+JSON.stringify(config)+' cannot mutate',async()=>{const p=await page(config);assert.match(p.notice(),/could not be loaded/);await p.handler('create')();assert.equal(nodes(p.render()).filter(n=>n.props?.name==='campaign-status-campaign').length,0);assert.equal(p.writes().length,0);assert.ok(nodes(p.render()).find(n=>n.type==='fieldset')?.props.disabled);});
test('Renders do not refetch; successful write refreshes exactly once',async()=>{const p=await page();await p.settle();assert.equal(p.calls.length,2);await p.handler('create')();await p.settle();assert.equal(p.calls.length,4);});
