// Actual TSX with controlled hooks, HTTP and window.print. Not browser/SQL/PDF proof.
const fs = require('node:fs'), assert = require('node:assert/strict'), { test } = require('node:test');
const ts = require('../../apps/web/node_modules/typescript'), jsx = require('../../apps/web/node_modules/react/jsx-runtime');
const code = ts.transpileModule(fs.readFileSync('apps/web/src/app/certificates/page.tsx', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, target: ts.ScriptTarget.ES2022 } }).outputText;
const baseline = process.env.QA_CERTIFICATE_PRINT_BASELINE === '1';
const saved = { id: 'c1', studentId: 's1', batchId: 'b1', certificateNumber: 'CERT-SYNTHETIC-001', verificationCode: 'VERIFIED-SYNTHETIC', title: 'Saved achievement', templateKey: 'school-merit', issuedDate: '2020-02-29', status: 'Issued', notes: 'Saved recognition' };
const students = [{ id: 's1', firstName: 'Saved', lastName: 'Learner' }, { id: 's2', firstName: 'Other', lastName: 'Learner' }];
const batches = [{ id: 'b1', name: 'Saved programme' }, { id: 'b2', name: 'Other programme' }];
const branding = { academyName: 'Saved Academy', accentColor: '#0F6CBD', signatoryName: 'Saved Signatory', logoUrl: null };
const nodes = x => !x || typeof x !== 'object' ? [] : Array.isArray(x) ? x.flatMap(nodes) : [x, ...nodes(x.props?.children)];
const text = x => x == null ? '' : Array.isArray(x) ? x.map(text).join(' ') : typeof x === 'object' ? text(x.props?.children) : String(x);
async function page(config = {}) {
  const state = [], refs = [], effects = [], deps = [], callbacks = [], callbackDeps = [], cleanups = [], calls = [], prints = [], listeners = new Map(); let i, r, e, c, releaseRead, written = false;
  const react = {
    useState(initial) { const k = i++; if (!(k in state)) state[k] = typeof initial === 'function' ? initial() : initial; return [state[k], value => state[k] = typeof value === 'function' ? value(state[k]) : value]; },
    useRef(initial) { const k = r++; return refs[k] ??= { current: initial }; },
    useMemo(fn) { return fn(); },
    useCallback(fn, next) { const k = c++; if (!callbackDeps[k] || next.some((v, j) => v !== callbackDeps[k][j])) { callbackDeps[k] = next; callbacks[k] = fn; } return callbacks[k]; },
    useEffect(fn, next) { const k = e++; if (!deps[k] || next.some((v, j) => v !== deps[k][j])) { deps[k] = next; effects.push(() => { cleanups[k]?.(); cleanups[k] = fn(); }); } },
  };
  const api = async (url, init = {}) => {
    calls.push({ url, ...init });
    if (init.method) { if (config.issueNetwork) throw Error('offline'); if (config.issueDenied) return { ok: false, json: async () => ({ message: 'Synthetic issuance rejected' }) }; written = true; return { ok: true, json: async () => { if (config.issueBadJson) throw Error('json'); return config.issueResult ?? saved; } }; }
    if (config.deferRead && url.endsWith('/certificates')) await new Promise(resolve => releaseRead = resolve);
    if (config.readNetwork) throw Error('offline');
    if (config.readDenied || (written && config.refreshDenied)) return { ok: false, json: async () => [] };
    const value = url === '/api/academies' ? [{ id: 'owned' }] : url.endsWith('/students') ? config.students ?? students : url.endsWith('/batches') ? config.batches ?? batches : url.endsWith('/enrollments') ? [{ studentId: 's1', batchId: 'b1', status: 'Active' }] : url.endsWith('/branding') ? config.branding === undefined ? branding : config.branding : config.certificates ?? (written ? [saved] : []);
    return { ok: true, json: async () => { if (config.readJson) throw Error('invalid JSON'); return config.readMalformed ? {} : value; } };
  };
  const mod = { exports: {} };
  const win = { print() { if (config.printThrows) throw Error('print unavailable'); prints.push(article()); }, addEventListener(name, fn) { listeners.set(name, fn); }, removeEventListener(name, fn) { if (listeners.get(name) === fn) listeners.delete(name); } };
  new Function('require', 'module', 'exports', 'window', code)(name => name === 'react' ? react : name === 'react/jsx-runtime' ? jsx : name === '@/lib/api' ? { academyApi: api, apiHeaders: () => ({}), apiUrl: 'http://qa.invalid' } : name === '@/components/workspace-nav' ? { WorkspaceNav: 'nav' } : name === '@/components/enterprise-page-state' ? { EnterprisePageState: 'notice' } : name === '@/components/design-system/controls' ? { StandardSelectField: 'select', StandardDateField: 'date' } : (() => { throw Error(name); })(), mod, mod.exports, win);
  const render = () => { i = r = e = c = 0; return mod.exports.default(); };
  const flush = async () => { for (let n = 0; n < 7; n++) { effects.splice(0).forEach(fn => fn()); await new Promise(resolve => setImmediate(resolve)); render(); } };
  const article = () => nodes(render()).find(x => x.type === 'article' && x.props.className?.includes('certificate-preview'));
  const form = () => nodes(render()).find(x => x.type === 'form' && x.props.className?.includes('certificate-issue-form'));
  const control = name => nodes(render()).find(x => x.props?.name === name);
  const change = (name, value) => { const node = control(name); assert.ok(node, 'Missing control: ' + name); node.props.onChange(node.type === 'select' || node.type === 'date' ? value : { target: { value } }); render(); };
  const button = () => nodes(render()).find(x => x.type === 'button' && /Print \/ save PDF/.test(text(x)));
  render(); await flush();
  return { render, flush, config, calls, prints, article, button, control, change, print: () => button().props.onClick(), close: () => listeners.get('afterprint')?.(), releaseRead: () => releaseRead?.(), submit: () => form().props.onSubmit({ preventDefault() {} }), refresh: () => nodes(render()).find(x => x.type === 'button' && text(x) === 'Refresh records').props.onClick(), message: () => text(nodes(render()).filter(x => x.type === 'notice')) };
}
test('draft cannot use official Print button and remains visibly marked', async () => {
  const h = await page(); assert.equal(h.button().props.disabled, true); await h.print(); await h.flush(); assert.equal(h.prints.length, 0); assert.match(text(h.article()), /PREVIEW.*NOT.*ISSUED PRINT/);
});
test('saved print ignores later learner/class/title/theme/date/note draft edits', async () => {
  const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); h.change('studentId', 's2'); h.change('batchId', 'b2'); h.change('title', 'Unsaved title'); h.change('themeKey', 'holiday-diwali'); h.change('issuedDate', '2030-01-01'); h.change('notes', 'Unsaved note'); await h.print(); await h.flush();
  assert.equal(h.prints.length, 1); const output = text(h.prints[0]); for (const value of ['Saved learner', 'Saved programme', 'Saved achievement', '2020-02-29', 'Saved recognition']) assert.match(output.toLowerCase(), new RegExp(value.toLowerCase())); assert.doesNotMatch(output, /Unsaved|2030-01-01|Other learner/); assert.match(h.prints[0].props.className, /theme-school-merit/);
});
test('print includes saved certificate number verification identity and Issued status', async () => {
  const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); await h.print(); await h.flush(); assert.equal(h.prints.length, 1); const output = text(h.prints[0]); for (const value of [saved.certificateNumber, saved.verificationCode, 'Issued']) assert.ok(output.includes(value)); assert.equal(h.prints[0].props['data-print-state'], 'issued');
});
test('revoked record cannot print even through a stale or manually invoked callback', async () => {
  const h = await page({ certificates: [{ ...saved, status: 'Revoked' }] }); if (h.control('printCertificateId')) h.change('printCertificateId', 'c1'); assert.equal(h.button().props.disabled, true); await h.print(); await h.flush(); assert.equal(h.prints.length, 0);
});
if (!baseline) {
  for (const status of ['Replaced', 'Unknown', '', null]) test('non-issued stored status blocked ' + JSON.stringify(status), async () => { const h = await page({ certificates: [{ ...saved, status }] }); h.change('printCertificateId', 'c1'); await h.print(); await h.flush(); assert.equal(h.prints.length, 0); assert.equal(h.button().props.disabled, true); });
  for (const status of ['Issued', 'issued', 'ISSUED']) test('supported issued status casing ' + status, async () => { const h = await page({ certificates: [{ ...saved, status }] }); h.change('printCertificateId', 'c1'); await h.print(); await h.flush(); assert.equal(h.prints.length, 1); h.close(); await h.flush(); assert.equal(h.article().props['data-print-state'], 'preview'); });
  for (const change of [{ status: 'Revoked' }, { status: 'Replaced' }, null]) test('fresh status/removal prevents cached print ' + JSON.stringify(change), async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); h.config.certificates = change ? [{ ...saved, ...change }] : []; await h.print(); await h.flush(); assert.equal(h.prints.length, 0); assert.match(h.message(), /no longer available for printing/); });
  for (const failure of ['readDenied', 'readNetwork', 'readJson', 'readMalformed']) test('fresh read failure prints nothing and preserves issue draft ' + failure, async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); h.change('notes', 'Retain'); h.config[failure] = true; await h.print(); await h.flush(); assert.equal(h.prints.length, 0); assert.equal(h.control('notes').props.value, 'Retain'); assert.match(h.message(), /could not be verified/); assert.equal(h.article().props['data-print-state'], 'preview'); h.config[failure] = false; await h.print(); await h.flush(); assert.equal(h.prints.length, 1); });
  for (const change of [{ certificateNumber: '' }, { verificationCode: '' }, { issuedDate: '2026-02-30' }, { title: '' }, { templateKey: 'unknown' }, { batchId: 'missing' }, { batchId: undefined }, { studentId: 'missing' }, { notes: 42 }]) test('incomplete/unresolvable record is not printable ' + JSON.stringify(change), async () => { const h = await page({ certificates: [{ ...saved, ...change }] }); h.change('printCertificateId', 'c1'); await h.print(); await h.flush(); assert.equal(h.prints.length, 0); assert.equal(h.button().props.disabled, true); });
  test('independent saved certificate does not borrow draft class', async () => { const h = await page({ certificates: [{ ...saved, batchId: null }] }); h.change('printCertificateId', 'c1'); h.change('batchId', 'b1'); await h.print(); await h.flush(); assert.match(text(h.prints[0]), /Independent programme/); assert.doesNotMatch(text(h.prints[0]), /Saved programme/); });
  test('confirmed issuance selects its returned saved identity,not the first register row', async () => { const h = await page(); h.config.certificates = [{ ...saved, id: 'c2', certificateNumber: 'CERT-OTHER' }, saved]; await h.submit(); await h.flush(); assert.equal(h.control('printCertificateId').props.value, 'c1'); await h.print(); await h.flush(); assert.equal(h.prints.length, 1); assert.ok(text(h.prints[0]).includes(saved.certificateNumber)); assert.doesNotMatch(text(h.prints[0]), /CERT-OTHER/); });
  for (const mode of ['issueDenied', 'issueNetwork', 'issueBadJson', 'refreshDenied']) test('failed/uncertain/malformed/readback-unavailable issue cannot authorize a print ' + mode, async () => { const h = await page(); h.config[mode] = true; await h.submit(); await h.flush(); await h.print(); await h.flush(); assert.equal(h.prints.length, 0); assert.equal(h.button().props.disabled, true); });
  test('new failed issue does not masquerade as the previously selected issuance', async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); h.config.issueDenied = true; await h.submit(); await h.flush(); assert.equal(h.control('printCertificateId').props.value, ''); assert.equal(h.button().props.disabled, true); });
  test('print verifies all four reads no-store in current academy,no POST', async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); const start = h.calls.length; await h.print(); await h.flush(); const calls = h.calls.slice(start); assert.equal(calls.length, 4); assert.ok(calls.every(x => x.url.startsWith('/api/academies/owned/') && x.cache === 'no-store' && !x.method)); });
  test('pending print blocks duplicate print/issue/refresh/stale selection callbacks', async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); h.config.deferRead = true; const pending = h.print(); await h.flush(); const count = h.calls.length; await h.print(); await h.submit(); await h.refresh(); h.change('printCertificateId', 'other'); assert.equal(h.calls.length, count); assert.equal(h.control('printCertificateId').props.value, 'c1'); h.releaseRead(); await pending; await h.flush(); assert.equal(h.prints.length, 1); });
  test('fresh saved references/branding used,not unsaved branding edits', async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); const labels = nodes(h.render()).filter(x => x.type === 'input'); labels.find(x => x.props.type === 'color').props.onChange({ target: { value: '#FFFFFF' } }); labels.find(x => x.props.placeholder === 'Signatory name').props.onChange({ target: { value: 'Unsaved Signatory' } }); h.config.branding = { ...branding, academyName: 'Current Saved Academy', signatoryName: 'Current Saved Signatory', accentColor: '#123456' }; await h.print(); await h.flush(); assert.match(text(h.prints[0]), /Current Saved Academy|Current Saved Signatory/); assert.doesNotMatch(text(h.prints[0]), /Unsaved Signatory/); assert.equal(h.prints[0].props.style['--academy-certificate-accent'], '#123456'); });
  test('afterprint clears official approval,does not claim PDF saved,and allows another verified print', async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); await h.print(); await h.flush(); h.close(); await h.flush(); assert.equal(h.article().props['data-print-state'], 'preview'); assert.match(h.message(), /Print dialog closed/); assert.doesNotMatch(h.message(), /PDF saved|printed successfully/); await h.print(); await h.flush(); assert.equal(h.prints.length, 2); });
  test('native print error clears official approval and unlocks retry', async () => { const h = await page({ certificates: [saved], printThrows: true }); h.change('printCertificateId', 'c1'); await h.print(); await h.flush(); assert.equal(h.prints.length, 0); assert.equal(h.article().props['data-print-state'], 'preview'); assert.match(h.message(), /Print dialog could not be opened/); h.config.printThrows = false; await h.print(); await h.flush(); assert.equal(h.prints.length, 1); });
  test('fresh stored fields replace cached fields and no unsaved note leaks into null saved notes', async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); h.change('notes', 'Unsaved secret note'); h.config.certificates = [{ ...saved, title: 'Current saved title', issuedDate: '2021-01-02', templateKey: 'music-rhythm', notes: null, certificateNumber: 'CERT-CURRENT', verificationCode: 'CURRENT-CODE' }]; await h.print(); await h.flush(); const output = text(h.prints[0]); assert.match(output, /Current saved title/); assert.ok(output.includes('CERT-CURRENT') && output.includes('CURRENT-CODE') && output.includes('2021-01-02')); assert.doesNotMatch(output, /Unsaved secret note|Saved recognition|Saved achievement/); assert.match(h.prints[0].props.className, /theme-music-rhythm/); });
  test('no selected issuance does not default to the first saved row', async () => { const h = await page({ certificates: [saved] }); assert.equal(h.control('printCertificateId').props.value, ''); assert.equal(h.button().props.disabled, true); await h.print(); await h.flush(); assert.equal(h.prints.length, 0); });
  for (const invalid of [null, { ...branding, academyName: '' }, { ...branding, accentColor: '#bad' }, { ...branding, signatoryName: 42 }, { ...branding, logoUrl: 42 }]) test('fresh invalid branding never authorizes official output ' + JSON.stringify(invalid), async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); h.config.branding = invalid; await h.print(); await h.flush(); assert.equal(h.prints.length, 0); assert.equal(h.article().props['data-print-state'], 'preview'); });
  for (const change of [{ firstName: '', lastName: '' }, { firstName: null }, { lastName: 42 }]) test('fresh unresolved learner name never uses a guessed printable name ' + JSON.stringify(change), async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); h.config.students = [{ ...students[0], ...change }]; await h.print(); await h.flush(); assert.equal(h.prints.length, 0); });
  test('manual print-preparation close restores a watermarked preview and unlocks', async () => { const h = await page({ certificates: [saved] }); h.change('printCertificateId', 'c1'); await h.print(); await h.flush(); const close = nodes(h.render()).find(x => x.type === 'button' && text(x) === 'Close print preparation'); close.props.onClick(); await h.flush(); assert.equal(h.article().props['data-print-state'], 'preview'); assert.equal(h.button().props.disabled, false); });
}
