// Reuse all 50 accepted channel-choice cases and their actual-TSX harness unchanged.
const test=require('node:test'),assert=require('node:assert/strict');
const {page,nodes,people}=require('./communication-channel.test.cjs');
const tick=()=>new Promise(r=>setImmediate(r));
async function draft(config={},banner=false){const p=await page(config);if(banner)p.select('recipientType','Academy');else p.select('recipientId',people.Guardian);p.edit('Title','Synthetic title');p.edit('Message','Synthetic body');return p;}
for(const banner of[false,true])for(const empty of[false,true])test(`${banner?'banner':'direct'} durable success, empty body=${empty}`,async()=>{const p=await draft({empty},banner);await p.save();assert.equal(p.state.get(19),banner?'Important announcement will run for 4 hours.':'Message queued.');assert.equal(p.state.get(20),false);const notice=nodes(p.render()).find(n=>n.props?.role==='status');assert.equal(notice.props['aria-live'],'polite');assert.equal(p.writes().length,1);const body=JSON.parse(p.writes()[0].body);assert.equal(body.title,'Synthetic title');assert.equal(body.message,'Synthetic body');assert.equal(body.channel,'InApp');assert.equal(body.templateId,null);assert.equal(body.scheduledAtUtc,null);assert.deepEqual(body.variables,banner?{audiences:'Student,Teacher'}:{});assert.equal(body.displayHours,banner?4:null);assert.equal(body.isImportant,banner);for(const k of[7,8,10,11,13,14,16])assert.equal(p.state.get(k),'');assert.equal(p.state.get(17),'09:00');});
for(const banner of[false,true])test('Confirmed save with readback failure '+banner,async()=>{const p=await draft({refreshFailure:true},banner);await p.save();assert.match(p.state.get(19),/could not be refreshed.*do not repeat/);assert.match(p.state.get(19),banner?/^Important announcement/:/^Message queued/);assert.equal(p.state.get(10),'');assert.equal(p.state.get(20),false);});
for(const status of[400,403,500,503])for(const banner of[false,true])test('HTTP '+status+' retention '+banner,async()=>{const p=await draft({status,message:'Synthetic guidance'},banner);await p.save();assert.match(p.state.get(19),/Synthetic guidance/);if(status>=500)assert.match(p.state.get(19),/could not be confirmed.*before retrying/);assert.equal(p.state.get(10),'Synthetic title');assert.equal(p.state.get(11),'Synthetic body');assert.equal(p.state.get(20),false);assert.equal(p.calls.length,7);assert.equal(p.writes().length,1);});
for(const banner of[false,true])test('Network uncertainty '+banner,async()=>{const p=await draft({network:true},banner);await p.save();assert.match(p.state.get(19),/could not be confirmed.*before retrying/);assert.equal(p.state.get(11),'Synthetic body');assert.equal(p.state.get(20),false);});
for(const config of[{empty:true},{message:'   '},{message:123}])test('Rejection fallback '+JSON.stringify(config),async()=>{const p=await draft({status:400,...config});await p.save();assert.equal(p.state.get(19),'Message could not be queued.');assert.equal(p.state.get(20),false);});
for(const stage of['write','readback'])test(stage+' stale handler duplicate guard',async()=>{let release;const gate=new Promise(r=>release=r),p=await draft(stage==='write'?{writeGate:gate}:{readGate:gate});const handler=nodes(p.render()).find(n=>n.type==='form').props.onSubmit,first=handler({preventDefault(){}});await tick();const second=handler({preventDefault(){}});try{assert.equal(p.writes().length,1);assert.equal(nodes(p.render()).find(n=>n.type==='fieldset').props.disabled,true);assert.equal(nodes(p.render()).find(n=>n.type==='button').props.disabled,true);}finally{release();}await Promise.all([first,second]);assert.equal(p.state.get(20),false);assert.equal(p.writes().length,1);});
test('Mount requests remain stable through draft/pending/notice state',async()=>{const p=await draft();await p.flush();assert.equal(p.calls.length,6);await p.save();await p.flush();assert.equal(p.calls.length,12);await p.flush();assert.equal(p.calls.length,12);});
