// Actual TSX with controlled hooks/transport, not live SQL/device acceptance.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const ts=require('../../apps/web/node_modules/typescript'),jsx=require('../../apps/web/node_modules/react/jsx-runtime');
const source=process.env.QA_EVENTS_BASELINE==='1'?require('node:child_process').execFileSync('git',['show','HEAD:apps/web/src/app/events/page.tsx'],{encoding:'utf8'}):fs.readFileSync('apps/web/src/app/events/page.tsx','utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
function nodes(n){return Array.isArray(n)?n.flatMap(nodes):!n||typeof n!=='object'?[]:[n,...nodes(n.props?.children)];}
function text(n){return Array.isArray(n)?n.map(text).join(''):n==null||typeof n==='boolean'?'':typeof n==='object'?text(n.props?.children):String(n);}
const tick=()=>new Promise(r=>setImmediate(r));
async function page(config={}){
 let index=0,refIndex=0,effectIndex=0;const state=new Map(),refs=[],deps=[],effects=[],calls=[],module={exports:{}};
 const react={useState:v=>{const k=index++;if(!state.has(k))state.set(k,v);return[state.get(k),v=>state.set(k,typeof v==='function'?v(state.get(k)):v)];},useRef:v=>{const k=refIndex++;return refs[k]??(refs[k]={current:v});},useEffect:(fn,next)=>{const k=effectIndex++;if(!deps[k]||next.some((v,i)=>v!==deps[k][i])){deps[k]=next;effects.push(fn);}}};
 const api=async(url,init={})=>{
  calls.push({url,...init});if(init.method){if(config.writeGate)await config.writeGate;if(config.network)throw Error('Synthetic network');return{ok:!config.status,status:config.status||200,json:async()=>{if(config.malformed)throw Error('Malformed');return{message:config.message};}};}
  if(url==='/api/academies')return{ok:true,json:async()=>[{id:'owned'}]};
  if(calls.some(c=>c.method)){if(config.readGate)await config.readGate;if(config.refreshFailure)return{ok:false,status:503};}
  assert.ok(['/api/academies/owned/events','/api/academies/owned/branches'].includes(url));return{ok:true,json:async()=>[]};
 };
 new Function('require','module','exports',code)(n=>n==='react/jsx-runtime'?jsx:n==='react'?react:n==='@/lib/api'?{academyApi:api,apiHeaders:()=>({})}:n==='@/components/workspace-nav'?{WorkspaceNav:'nav'}:n==='@/components/design-system/controls'?{StandardDateField:'date',StandardTimeField:'time',StandardSelectField:'select'}:(()=>{throw Error(n)})(),module,module.exports);
 const render=()=>{index=refIndex=effectIndex=0;return module.exports.default();};
 async function settle(){for(let i=0;i<4;i++){for(const fn of effects.splice(0))fn();await tick();render();}}
 const action=()=>nodes(render()).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});
 render();await settle();for(const[k,v]of[[3,'Draft event'],[4,'Workshop'],[5,'branch-fixture'],[6,'2026-10-31'],[8,'2026-10-31'],[10,'Fixture room']])state.set(k,v);
 return{state,calls,render,settle,action,writes:()=>calls.filter(c=>c.method)};
}
test('Durable accessible success and original payload/reset contract',async()=>{const p=await page();await p.action();await p.settle();assert.equal(p.state.get(11),'Event planned.');assert.equal(p.state.get(12),false);const n=nodes(p.render()).find(n=>n.props?.role==='status');assert.equal(n.props['aria-live'],'polite');assert.equal(text(n),'Event planned.');assert.deepEqual(JSON.parse(p.writes()[0].body),{title:'Draft event',type:'Workshop',branchId:'branch-fixture',startUtc:new Date('2026-10-31T10:00:00').toISOString(),endUtc:new Date('2026-10-31T11:00:00').toISOString(),venue:'Fixture room',capacity:null,notes:null});for(const k of[3,6,8,10])assert.equal(p.state.get(k),'');assert.equal(p.state.get(4),'Workshop');assert.equal(p.state.get(5),'branch-fixture');assert.equal(p.state.get(7),'10:00');assert.equal(p.state.get(9),'11:00');});
test('Saved/readback failure is not a failed write',async()=>{const p=await page({refreshFailure:true});await p.action();assert.match(p.state.get(11),/^Event planned.*could not be refreshed.*do not repeat/);assert.equal(p.state.get(3),'');assert.equal(p.state.get(12),false);assert.equal(p.writes().length,1);});
for(const status of[400,403,500,503])test('HTTP '+status+' retains draft and guidance without retries',async()=>{const p=await page({status,message:'Synthetic service guidance'});await p.action();assert.match(p.state.get(11),/Synthetic service guidance/);if(status>=500)assert.match(p.state.get(11),/could not be confirmed.*before retrying/);for(const[k,v]of[[3,'Draft event'],[6,'2026-10-31'],[8,'2026-10-31'],[10,'Fixture room']])assert.equal(p.state.get(k),v);assert.equal(p.state.get(12),false);assert.equal(p.calls.length,4);assert.equal(p.writes().length,1);});
test('Network uncertainty is caught and draft retained',async()=>{const p=await page({network:true});await p.action();assert.match(p.state.get(11),/could not be confirmed.*before retrying/);assert.equal(p.state.get(3),'Draft event');assert.equal(p.state.get(12),false);});
for(const config of[{malformed:true},{message:''},{message:'   '},{message:123}])test('Rejection fallback '+JSON.stringify(config),async()=>{const p=await page({status:400,...config});await p.action();assert.equal(p.state.get(11),'Enter a title and valid start/end times.');assert.equal(p.state.get(12),false);});
for(const stage of['write','readback'])test(stage+' pending guard includes same-tick stale handler',async()=>{let release;const gate=new Promise(r=>release=r),p=await page(stage==='write'?{writeGate:gate}:{readGate:gate});const handler=nodes(p.render()).find(n=>n.type==='form').props.onSubmit,first=handler({preventDefault(){}});await tick();const second=handler({preventDefault(){}});try{assert.equal(p.writes().length,1);assert.ok(nodes(p.render()).filter(n=>['button','input','fieldset','select'].includes(n.type)).every(n=>n.props.disabled));}finally{release();}await Promise.all([first,second]);assert.equal(p.writes().length,1);assert.equal(p.state.get(12),false);});
test('Optional blanks and default type/time preserve null contract',async()=>{const p=await page();p.state.set(4,'Recital');p.state.set(5,'');p.state.set(10,'');await p.action();const body=JSON.parse(p.writes()[0].body);assert.equal(body.branchId,null);assert.equal(body.venue,null);assert.equal(body.type,'Recital');assert.equal(body.startUtc,new Date('2026-10-31T10:00:00').toISOString());});
test('State transitions do not reload mount data',async()=>{const p=await page();await p.settle();assert.equal(p.calls.length,3);await p.action();await p.settle();assert.equal(p.calls.length,6);await p.settle();assert.equal(p.calls.length,6);});
