// Actual TSX handlers, synthetic hooks/API/confirm. Not live admissions/SQL proof.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const ts=require('../../apps/web/node_modules/typescript'),jsx=require('../../apps/web/node_modules/react/jsx-runtime');
const source=process.env.QA_LEADS_BASELINE==='1'?require('node:child_process').execFileSync('git',['show','HEAD:apps/web/src/app/leads/page.tsx'],{encoding:'utf8'}):fs.readFileSync('apps/web/src/app/leads/page.tsx','utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
function nodes(n){return Array.isArray(n)?n.flatMap(nodes):!n||typeof n!=='object'?[]:[n,...nodes(n.props?.children)];}
const tick=()=>new Promise(r=>setImmediate(r));
async function page(config={}){
 let index=0,refIndex=0,effectIndex=0;const state=new Map(),refs=[],deps=[],effects=[],calls=[],confirms=[],module={exports:{}};
 const lead={id:'lead',fullName:'Synthetic lead',source:'Website',stage:'New',followUpAtUtc:config.nullFollowUp?null:'2026-10-31T10:00:00Z',convertedStudentId:config.converted?'student':null};
 const react={useState:v=>{const k=index++;if(!state.has(k))state.set(k,v);return[state.get(k),v=>state.set(k,typeof v==='function'?v(state.get(k)):v)];},useRef:v=>{const k=refIndex++;return refs[k]??(refs[k]={current:v});},useEffect:(fn,next)=>{const k=effectIndex++;if(!deps[k]||next.some((v,i)=>v!==deps[k][i])){deps[k]=next;effects.push(fn);}}};
 const api=async(url,init={})=>{
  calls.push({url,...init});if(init.method){if(config.writeGate)await config.writeGate;if(config.network)throw Error('Synthetic network');return{ok:!config.status,status:config.status||200};}
  assert.equal(init.cache,'no-store');if(url==='/api/academies')return{ok:!config.academyStatus,status:config.academyStatus||200,json:async()=>config.noAcademy?[]:[{id:'owned'}]};
  assert.equal(url,'/api/academies/owned/leads');if(calls.some(c=>c.method)){if(config.readGate)await config.readGate;if(config.refreshFailure)return{ok:false,status:503};}
  return{ok:!config.initialFailure,json:async()=>config.malformed?{}:[lead]};
 };
 new Function('require','module','exports','window',code)(n=>n==='react/jsx-runtime'?jsx:n==='react'?react:n==='@/lib/api'?{academyApi:api,apiHeaders:()=>({})}:n==='@/components/workspace-nav'?{WorkspaceNav:'nav'}:n==='@/components/design-system/controls'?{StandardSelectField:'select',StandardDateField:'date',StandardTimeField:'time'}:(()=>{throw Error(n)})(),module,module.exports,{confirm:message=>{confirms.push(message);return !config.cancel;}});
 const render=()=>{index=refIndex=effectIndex=0;return module.exports.default();};
 async function settle(){for(let i=0;i<5;i++){for(const fn of effects.splice(0))fn();await tick();render();}}
 render();await settle();for(const[k,v]of[[2,' Draft lead '],[3,'fixture@example.test'],[4,'synthetic-phone'],[5,'2010-10-31'],[6,'Synthetic parent'],[7,'Guitar'],[8,'Instagram'],[9,'2026-10-31'],[10,'11:15'],[11,' Synthetic notes ']])state.set(k,config.blank&&![2,8,10].includes(k)?'':v);
 const handler=kind=>{const tree=nodes(render());if(kind==='create'){const h=tree.find(n=>n.type==='form').props.onSubmit;return()=>h({preventDefault(){}});}const h=kind==='stage'?tree.find(n=>n.props?.name==='lead-stage-lead').props.onChange:tree.find(n=>n.type==='button'&&n.props.type==='button').props.onClick;return async()=>{h('FollowUp');await settle();};};
 return{state,calls,confirms,lead,render,settle,handler,writes:()=>calls.filter(c=>c.method),notice:()=>state.get(12)};
}
const success={create:'Lead added to the pipeline.',stage:'Synthetic lead moved to Follow-up.',convert:'Synthetic lead was converted to a student. You can now enrol them in a batch.'};
for(const kind of['create','stage','convert']){
 test(kind+' durable polite success, exact fields and matching reset',async()=>{const p=await page();await p.handler(kind)();await p.settle();assert.equal(p.notice(),success[kind]);const w=p.writes()[0];assert.equal(w.url,'/api/academies/owned/leads'+(kind==='create'?'':kind==='stage'?'/lead/stage':'/lead/convert'));assert.equal(w.method,kind==='stage'?'PATCH':'POST');assert.deepEqual(JSON.parse(w.body),kind==='stage'?{stage:'FollowUp',followUpAtUtc:p.lead.followUpAtUtc}:kind==='convert'?{firstName:null,lastName:null}:{fullName:' Draft lead ',email:'fixture@example.test',phone:'synthetic-phone',dateOfBirth:'2010-10-31',parentName:'Synthetic parent',programInterest:'Guitar',source:'Instagram',followUpAtUtc:new Date('2026-10-31T11:15:00').toISOString(),notes:' Synthetic notes '});assert.equal(p.state.get(2),kind==='create'?'':' Draft lead ');assert.equal(p.state.get(8),'Instagram');assert.equal(p.state.get(10),kind==='create'?'10:00':'11:15');assert.equal(p.state.get(13),'');assert.equal(nodes(p.render()).find(n=>n.props?.role==='status').props['aria-live'],'polite');assert.equal(p.confirms.length,kind==='convert'?1:0);});
 test(kind+' confirmed save survives failed refresh',async()=>{const p=await page({refreshFailure:true});await p.handler(kind)();assert.ok(p.notice().startsWith(success[kind]));assert.match(p.notice(),/could not be refreshed; do not repeat/);assert.equal(p.state.get(2),kind==='create'?'':' Draft lead ');assert.equal(p.writes().length,1);assert.equal(p.state.get(13),'');});
 for(const status of[400,403,500,503])test(kind+' HTTP '+status+' retains draft and no retry',async()=>{const p=await page({status});await p.handler(kind)();assert.match(p.notice(),status>=500?/could not be confirmed.*before retrying/:/could not/);assert.equal(p.state.get(2),' Draft lead ');assert.equal(p.state.get(11),' Synthetic notes ');assert.equal(p.calls.length,3);assert.equal(p.writes().length,1);assert.equal(p.state.get(13),'');});
 test(kind+' network uncertainty caught',async()=>{const p=await page({network:true});await p.handler(kind)();assert.match(p.notice(),/could not be confirmed.*retained.*before retrying/);assert.equal(p.state.get(2),' Draft lead ');assert.equal(p.writes().length,1);assert.equal(p.state.get(13),'');});
 for(const stage of['write','readback'])test(kind+' '+stage+' guards duplicate/opposing stale handlers',async()=>{let release;const gate=new Promise(r=>release=r),p=await page(stage==='write'?{writeGate:gate}:{readGate:gate});p.state.set(12,'Old error');const h=p.handler(kind),other=p.handler(kind==='create'?'convert':'create'),first=h();await tick();const second=h(),third=other(),settled=Promise.allSettled([first,second,third]);try{assert.equal(p.writes().length,1);const tree=nodes(p.render());assert.ok(tree.find(n=>n.type==='fieldset')?.props.disabled);assert.ok(tree.filter(n=>n.type==='button'||n.type==='select').every(n=>n.props.disabled));assert.notEqual(p.notice(),'Old error');assert.equal(p.confirms.length,kind==='convert'?1:0);}finally{release();}for(const r of await settled)if(r.status==='rejected')throw r.reason;await p.settle();assert.equal(p.writes().length,1);assert.equal(p.state.get(13),'');});
}
test('Blank optional create fields remain null',async()=>{const p=await page({blank:true});await p.handler('create')();const b=JSON.parse(p.writes()[0].body);for(const k of['email','phone','dateOfBirth','parentName','programInterest','followUpAtUtc','notes'])assert.equal(b[k],null);assert.equal(b.source,'Instagram');});
test('Conversion cancellation preserves previous notice/draft and sends nothing',async()=>{const p=await page({cancel:true});p.state.set(12,'Previous notice');await p.handler('convert')();assert.equal(p.notice(),'Previous notice');assert.equal(p.state.get(2),' Draft lead ');assert.equal(p.writes().length,0);assert.deepEqual(p.confirms,['Convert Synthetic lead into a student record?']);});
test('Converted lead blocks stage and conversion with no confirmation',async()=>{const p=await page({converted:true});await p.handler('stage')();await p.handler('convert')();assert.equal(p.writes().length,0);assert.equal(p.confirms.length,0);});
test('Null existing follow-up remains null in stage request',async()=>{const p=await page({nullFollowUp:true});await p.handler('stage')();assert.deepEqual(JSON.parse(p.writes()[0].body),{stage:'FollowUp',followUpAtUtc:null});});
for(const config of[{noAcademy:true},{academyStatus:401},{academyStatus:403},{initialFailure:true},{malformed:true}])test('Unavailable initial workspace '+JSON.stringify(config)+' cannot create',async()=>{const p=await page(config);assert.match(p.notice(),/could not be loaded|Create your academy first|sign in/);await p.handler('create')();assert.equal(p.writes().length,0);assert.ok(nodes(p.render()).find(n=>n.type==='fieldset')?.props.disabled);});
test('Renders do not refetch; mutation refreshes lead list once',async()=>{const p=await page();await p.settle();assert.equal(p.calls.length,2);await p.handler('create')();await p.settle();assert.equal(p.calls.length,4);await p.settle();assert.equal(p.calls.length,4);});
