// Actual TSX handlers with synthetic hooks/API; not live SQL/finance acceptance.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const ts=require('../../apps/web/node_modules/typescript'),jsx=require('../../apps/web/node_modules/react/jsx-runtime');
const source=process.env.QA_PLATFORM_SERVICES_BASELINE==='1'?require('node:child_process').execFileSync('git',['show','HEAD:apps/web/src/app/platform-services/page.tsx'],{encoding:'utf8'}):fs.readFileSync('apps/web/src/app/platform-services/page.tsx','utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const invoice={id:'invoice',invoiceNumber:'Synthetic invoice',amount:1000,currency:'INR',status:'Open',periodStart:'2026-10-01',periodEnd:'2026-10-31',dueDate:'2026-10-31'};
const cases=[{id:'case',subject:'Synthetic case',priority:'Normal',status:'Open',createdAtUtc:'2026-10-10T12:00:00Z'},{id:'other',subject:'Other case',priority:'Normal',status:'Open',createdAtUtc:'2026-10-10T12:00:00Z'}];
function nodes(n){return Array.isArray(n)?n.flatMap(nodes):!n||typeof n!=='object'?[]:[n,...nodes(n.props?.children)];}
const tick=()=>new Promise(r=>setImmediate(r));
async function page(config={}){
 let index=0,refIndex=0,effectIndex=0,resets=0;const state=new Map(),refs=[],deps=[],effects=[],calls=[],module={exports:{}};
 const react={useState:v=>{const k=index++;if(!state.has(k))state.set(k,v);return[state.get(k),v=>state.set(k,typeof v==='function'?v(state.get(k)):v)];},useRef:v=>{const k=refIndex++;return refs[k]??(refs[k]={current:v});},useEffect:(fn,next)=>{const k=effectIndex++;if(!deps[k]||next.some((v,i)=>v!==deps[k][i])){deps[k]=next;effects.push(fn);}}};
 const api=async(url,init={})=>{
  calls.push({url,...init});if(init.method){assert.equal(init.method,'POST');if(config.writeGate)await config.writeGate;if(config.network)throw Error('Synthetic network');return{ok:!config.status,status:config.status||200};}
  if(calls.some(c=>c.method)){if(config.readGate)await config.readGate;if(config.refreshFailure)return{ok:false,status:503};}
  assert.equal(init.cache,'no-store');if(url==='/api/academies')return{ok:!config.academyFailure,json:async()=>config.noAcademy?[]:[{id:'owned',name:'Synthetic academy'}]};
  assert.ok(['/api/academies/owned/platform-services/billing-invoices','/api/academies/owned/platform-services/support-cases'].includes(url));return{ok:!config.initialFailure,json:async()=>config.malformed?{}:url.endsWith('billing-invoices')?[invoice]:cases};
 };
 class Form{constructor(element){assert.ok(element);}get(name){return name==='subject'?' Synthetic subject ':' Synthetic description ';}}
 new Function('require','module','exports','FormData',code)(n=>n==='react/jsx-runtime'?jsx:n==='react'?react:n==='@/lib/api'?{academyApi:api,apiHeaders:()=>({})}:n==='@/components/design-system/controls'?{StandardSelectField:'select'}:(()=>{throw Error(n)})(),module,module.exports,Form);
 const render=()=>{index=refIndex=effectIndex=0;return module.exports.default();};
 async function settle(){for(let i=0;i<5;i++){for(const fn of effects.splice(0))fn();await tick();render();}}
 render();await settle();state.set(5,'High');state.set(6,{invoice:config.blank?'':' Reference '});state.set(7,{case:config.blank?'   ':' Synthetic update ',other:'Other draft'});
 const event=()=>{let element={reset(){resets++;}};queueMicrotask(()=>element=null);return{preventDefault(){},get currentTarget(){return element;}};};
 const handler=kind=>{const tree=nodes(render());if(kind==='create'){const h=tree.find(n=>n.type==='form').props.onSubmit;return()=>h(event());}const h=tree.find(n=>n.type==='button'&&n.props.children===(kind==='payment'?'Submit payment':'Send update')).props.onClick;return async()=>{h();await settle();};};
 return{state,calls,render,settle,handler,resets:()=>resets,writes:()=>calls.filter(c=>c.method),notice:()=>state.get(3)};
}
const success={payment:'Payment submitted for Platform Owner review.',create:'Support request sent to the Platform Owner.',reply:'Response sent to the Platform Owner.'};
for(const kind of['payment','create','reply']){
 test(kind+' durable success, exact payload and only matching draft reset',async()=>{const p=await page();await p.handler(kind)();await p.settle();assert.equal(p.notice(),success[kind]);const write=p.writes()[0];assert.equal(write.url,'/api/academies/owned/platform-services/'+(kind==='payment'?'billing-invoices/invoice/payment-submission':kind==='reply'?'support-cases/case/response':'support-cases'));assert.deepEqual(JSON.parse(write.body),kind==='payment'?{reference:' Reference '}:kind==='reply'?{message:' Synthetic update '}:{subject:' Synthetic subject ',priority:'High',description:' Synthetic description '});assert.equal(p.resets(),kind==='create'?1:0);assert.equal(p.state.get(5),kind==='create'?'Normal':'High');assert.equal(p.state.get(6).invoice,' Reference ');assert.equal(p.state.get(7).case,kind==='reply'?'':' Synthetic update ');assert.equal(p.state.get(7).other,'Other draft');assert.equal(p.state.get(4),false);assert.equal(nodes(p.render()).find(n=>n.props?.role==='status').props['aria-live'],'polite');});
 test(kind+' confirmed save survives failed refresh',async()=>{const p=await page({refreshFailure:true});await p.handler(kind)();assert.ok(p.notice().startsWith(success[kind]));assert.match(p.notice(),/could not be refreshed; do not repeat/);assert.equal(p.resets(),kind==='create'?1:0);assert.equal(p.writes().length,1);assert.equal(p.state.get(4),false);});
 for(const status of[400,403,500,503])test(kind+' HTTP '+status+' retains all drafts',async()=>{const p=await page({status});await p.handler(kind)();assert.match(p.notice(),status>=500?/could not be confirmed.*before retrying/:/entries have been retained/);assert.equal(p.resets(),0);assert.equal(p.state.get(5),'High');assert.equal(p.state.get(6).invoice,' Reference ');assert.equal(p.state.get(7).case,' Synthetic update ');assert.equal(p.calls.length,4);assert.equal(p.writes().length,1);assert.equal(p.state.get(4),false);});
 test(kind+' network uncertainty caught without automatic retry',async()=>{const p=await page({network:true});await p.handler(kind)();assert.match(p.notice(),/could not be confirmed.*retained.*before retrying/);assert.equal(p.resets(),0);assert.equal(p.state.get(7).case,' Synthetic update ');assert.equal(p.writes().length,1);assert.equal(p.state.get(4),false);});
 for(const stage of['write','readback'])test(kind+' '+stage+' locks duplicate and opposing page actions',async()=>{let release;const gate=new Promise(r=>release=r),p=await page(stage==='write'?{writeGate:gate}:{readGate:gate});p.state.set(3,'Old error');const h=p.handler(kind),other=p.handler(kind==='create'?'payment':'create'),first=h();await tick();const second=h(),third=other(),settled=Promise.allSettled([first,second,third]);try{assert.equal(p.writes().length,1);assert.ok(nodes(p.render()).filter(n=>['button','input','textarea','select'].includes(n.type)).every(n=>n.props.disabled));assert.notEqual(p.notice(),'Old error');}finally{release();}for(const r of await settled)if(r.status==='rejected')throw r.reason;await p.settle();assert.equal(p.writes().length,1);assert.equal(p.state.get(4),false);});
}
test('Optional payment reference remains null',async()=>{const p=await page({blank:true});await p.handler('payment')();assert.deepEqual(JSON.parse(p.writes()[0].body),{reference:null});});
test('Whitespace-only reply sends nothing',async()=>{const p=await page({blank:true});await p.handler('reply')();assert.equal(p.writes().length,0);assert.equal(p.resets(),0);});
for(const config of[{noAcademy:true},{academyFailure:true},{initialFailure:true},{malformed:true}])test('Failed initial workspace '+JSON.stringify(config)+' cannot create',async()=>{const p=await page(config);assert.match(p.notice(),/could not be loaded/);await p.handler('create')();assert.equal(p.writes().length,0);assert.ok(nodes(p.render()).filter(n=>['button','input','textarea','select'].includes(n.type)).every(n=>n.props.disabled));});
test('Renders do not refetch; mutation refreshes once',async()=>{const p=await page();await p.settle();assert.equal(p.calls.length,3);await p.handler('create')();await p.settle();assert.equal(p.calls.length,7);await p.settle();assert.equal(p.calls.length,7);});
