// Reuse the ten accepted narrow-lookup/consent checks; synthetic transport only.
const test=require('node:test'),assert=require('node:assert/strict');
const {page,nodes}=require('./preference-access-ui.test.cjs');
const tick=()=>new Promise(r=>setImmediate(r));
async function draft(config={},type='Guardian'){const p=await page(config);p.select('recipientType',type);await p.flush();p.select('recipientId',type==='Student'?'student-id':'guardian-id');await p.flush();p.state[6]=false;p.state[7]=true;p.state[8]=false;p.state[9]='Synthetic opt-out notes';return p;}
for(const type of['Guardian','Student'])for(const empty of[false,true])test(type+' durable success empty='+empty,async()=>{const p=await draft({empty},type);await p.save();assert.equal(p.state[10],'Contact preferences saved.');assert.equal(p.state[11],false);const notice=nodes(p.render()).find(n=>n.props?.role==='status');assert.equal(notice.props['aria-live'],'polite');assert.equal(p.state[5],type==='Student'?'student-id':'guardian-id');assert.deepEqual(JSON.parse(p.calls.find(x=>x.method==='PUT').body),{emailAllowed:false,whatsAppAllowed:true,marketingAllowed:false,notes:'Synthetic opt-out notes'});assert.deepEqual(p.state.slice(6,10),[false,true,false,'Synthetic opt-out notes']);});
for(const type of['Guardian','Student'])test(type+' saved/readback failure retains confirmation and draft',async()=>{const p=await draft({refreshFailure:true},type);await p.save();assert.match(p.state[10],/^Contact preferences saved.*could not be refreshed.*do not repeat/);assert.deepEqual(p.state.slice(6,10),[false,true,false,'Synthetic opt-out notes']);assert.equal(p.state[11],false);});
for(const status of[400,403,500,503])test('HTTP '+status+' retains consent without retry',async()=>{const p=await draft({status,message:'Synthetic guidance'});await p.save();assert.match(p.state[10],/Synthetic guidance/);if(status>=500)assert.match(p.state[10],/could not be confirmed.*before retrying/);assert.deepEqual(p.state.slice(6,10),[false,true,false,'Synthetic opt-out notes']);assert.equal(p.state[11],false);assert.equal(p.calls.length,4);});
test('Network uncertainty caught',async()=>{const p=await draft({writeNetwork:true});await p.save();assert.match(p.state[10],/could not be confirmed.*before retrying/);assert.deepEqual(p.state.slice(6,10),[false,true,false,'Synthetic opt-out notes']);assert.equal(p.state[11],false);});
for(const config of[{empty:true},{message:'   '},{message:123}])test('Rejection fallback '+JSON.stringify(config),async()=>{const p=await draft({status:400,...config});await p.save();assert.equal(p.state[10],'Preference could not be saved.');assert.equal(p.state[11],false);});
for(const stage of['write','readback'])test(stage+' synchronous stale-handler duplicate guard',async()=>{let release;const gate=new Promise(r=>release=r),p=await draft(stage==='write'?{writeGate:gate}:{readGate:gate});const handler=nodes(p.render()).find(n=>n.type==='form').props.onSubmit,first=handler({preventDefault(){}});await tick();const duplicate=handler({preventDefault(){}});try{assert.equal(p.calls.filter(x=>x.method==='PUT').length,1);assert.equal(nodes(p.render()).find(n=>n.type==='fieldset').props.disabled,true);assert.equal(nodes(p.render()).find(n=>n.type==='button').props.disabled,true);}finally{release();}await Promise.all([first,duplicate]);assert.equal(p.state[11],false);});
test('Selection hydrates saved consent and clears unsaved contact fields',async()=>{const p=await draft();p.select('recipientType','Student');await p.flush();assert.equal(p.state[5],'');assert.deepEqual(p.state.slice(6,10),[false,false,false,'']);p.select('recipientId','student-id');await p.flush();assert.deepEqual(p.state.slice(6,10),[false,false,false,'']);p.select('recipientType','Guardian');p.select('recipientId','guardian-id');await p.flush();assert.deepEqual(p.state.slice(6,10),[true,false,true,'Existing consent']);});
test('Draft/save/notice do not rerun mount lookups',async()=>{const p=await draft();await p.flush();assert.equal(p.calls.length,3);await p.save();await p.flush();assert.equal(p.calls.length,6);await p.flush();assert.equal(p.calls.length,6);});
