// Actual TSX load/selection/save handlers, controlled hooks/API. Not browser evidence.
const fs=require('node:fs'),assert=require('node:assert/strict'),{test}=require('node:test');
const ts=require('../../apps/web/node_modules/typescript'),jsx=require('../../apps/web/node_modules/react/jsx-runtime');
const code=ts.transpileModule(process.env.QA_PREFERENCES_BASELINE==='1'?require('node:child_process').execFileSync('git',['show','HEAD:apps/web/src/app/communication-preferences/page.tsx'],{encoding:'utf8'}):fs.readFileSync('apps/web/src/app/communication-preferences/page.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
function nodes(x){return !x||typeof x!=='object'?[]:Array.isArray(x)?x.flatMap(nodes):[x,...nodes(x.props?.children)];}const text=x=>x==null?'':Array.isArray(x)?x.map(text).join(''):typeof x==='object'?text(x.props?.children):String(x);
const students=[{id:'student-id',firstName:'Synthetic',lastName:'Student',email:null}],guardians=[{id:'guardian-id',firstName:'Synthetic',lastName:'Parent',email:'recipient@example.invalid'}];
async function page(config={}){let i=0,e=0,r=0;const refs=[],state=[],deps=[],effects=[],calls=[],mod={exports:{}};let prefs=[{recipientType:'Guardian',recipientId:'guardian-id',emailAllowed:true,whatsAppAllowed:false,marketingAllowed:true,notes:'Existing consent'}];
 function StandardSelectField(){}
 const react={useRef:v=>{const k=r++;return refs[k]??(refs[k]={current:v});},useState:v=>{const k=i++;if(!(k in state))state[k]=v;return[state[k],v=>state[k]=typeof v==='function'?v(state[k]):v];},useMemo:f=>f(),useEffect:(fn,next)=>{const k=e++;if(!deps[k]||next.some((v,j)=>v!==deps[k][j])){deps[k]=next;effects.push(fn);}}};
 const api=async(url,init={})=>{calls.push({url,...init});if(url==='/api/academies')return{ok:true,json:async()=>[{id:'owned'}]};if(init.method==='PUT'){if(config.writeGate)await config.writeGate;if(config.writeNetwork)throw Error('Synthetic network');if(config.status)return{ok:false,status:config.status,json:async()=>{if(config.empty)throw Error('Empty');return{message:config.message};}};const parts=url.split('/'),p={recipientType:parts.at(-2),recipientId:parts.at(-1),...JSON.parse(init.body)};prefs=prefs.filter(x=>x.recipientId!==p.recipientId||x.recipientType!==p.recipientType).concat(p);return{ok:true,status:200,json:async()=>{if(config.empty)throw Error('Empty');return p;}};}if(calls.some(x=>x.method==='PUT')){if(config.readGate)await config.readGate;if(config.refreshFailure)return{ok:false,status:503};}
 if(url.endsWith('/students')||url.endsWith('/guardians'))return{ok:false,status:403,json:async()=>({})};
 if(url.endsWith('/recipients')){if(config.network)throw Error('offline');return{ok:!config.denied,status:config.denied?403:200,json:async()=>config.data??{students,guardians}};}
 return{ok:!config.preferenceDenied,status:config.preferenceDenied?403:200,json:async()=>prefs};};
 new Function('require','module','exports',code)(n=>n==='react/jsx-runtime'?jsx:n==='react'?react:n==='@/lib/api'?{academyApi:api,apiHeaders:()=>({})}:n==='@/components/workspace-nav'?{WorkspaceNav(){}}:n==='@/components/design-system/controls'?{StandardSelectField}:(()=>{throw Error(n);})(),mod,mod.exports);
 const render=()=>{i=e=r=0;return mod.exports.default();};const flush=async()=>{for(let t=0;t<5;t++){effects.splice(0).forEach(fn=>fn());await new Promise(r=>setImmediate(r));render();}};render();await flush();
 const select=(name,value)=>nodes(render()).find(n=>n.type===StandardSelectField&&n.props.name===name).props.onChange(value);
 const save=async()=>{await nodes(render()).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});await flush();};
 return{render,calls,select,flush,save,state,options:()=>nodes(render()).find(n=>n.type===StandardSelectField&&n.props.name==='recipientId').props.options};}
test('Manager page loads via narrow lookup, not forbidden broad people endpoints',async()=>{const h=await page();assert.equal(h.calls.filter(x=>x.url.endsWith('/recipients')).length,1);assert.equal(h.calls.filter(x=>x.url.endsWith('/students')||x.url.endsWith('/guardians')).length,0);assert.equal(h.options()[0].label,'Synthetic Parent · recipient@example.invalid');assert.equal(text(h.render()).includes('could not be loaded'),false);});
for(const config of [{denied:true},{network:true},{preferenceDenied:true},{data:{students:[],guardians:[]}},{data:{}},{data:{students:{},guardians:[]}},{data:{students:[],guardians:[{id:'bad',firstName:42,lastName:'Invalid'}]}}])test('lookup outcome '+JSON.stringify(config),async()=>{const h=await page(config);if(config.data?.students?.length===0&&config.data?.guardians?.length===0){assert.deepEqual(h.options(),[]);assert.equal(text(h.render()).includes('could not be loaded'),false);}else{assert.match(text(h.render()),/could not be loaded/);assert.equal(h.calls.some(x=>x.method==='PUT'),false);}});
for(const type of ['Guardian','Student'])test('contact selector and save retain existing consent contract '+type,async()=>{const h=await page();h.select('recipientType',type);await h.flush();h.select('recipientId',type==='Student'?'student-id':'guardian-id');await h.flush();assert.equal(h.options()[0].value,type==='Student'?'student-id':'guardian-id');await h.save();const call=h.calls.find(x=>x.method==='PUT');assert.equal(call.url,`/api/academies/owned/communication-preferences/${type}/${type==='Student'?'student-id':'guardian-id'}`);assert.deepEqual(JSON.parse(call.body),{emailAllowed:type==='Guardian',whatsAppAllowed:false,marketingAllowed:type==='Guardian',notes:type==='Guardian'?'Existing consent':''});assert.equal(h.calls.filter(x=>x.url.endsWith('/students')||x.url.endsWith('/guardians')).length,0);});
module.exports={page,nodes,text};
