// Deterministic overlapping actual api.ts calls, synthetic Map storage/fetch, no browser.
const fs=require('node:fs'),vm=require('node:vm'),a=require('node:assert/strict'),{test}=require('node:test');
const ts=require('../../apps/web/node_modules/typescript'),deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
async function tick(){await new Promise(r=>setImmediate(r));}
function harness(config={}){
 const events=new EventTarget();
 const storage=new Map(),calls=[],refreshes=[],window={location:{pathname:'/portal-accounts'},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)},addEventListener:events.addEventListener.bind(events),removeEventListener:events.removeEventListener.bind(events),dispatchEvent:events.dispatchEvent.bind(events)};
 const fetch=async(url,init={})=>{
  const call={url,init,headers:new Headers(init.headers)};calls.push(call);
  if(url.endsWith('/refresh')){const gate=deferred(),number=refreshes.length+1;refreshes.push({gate,call,number});await new Promise((resolve,reject)=>{const abort=()=>reject(Error('synthetic abort'));if(init.signal?.aborted)return abort();init.signal?.addEventListener('abort',abort,{once:true});gate.promise.then(()=>{init.signal?.removeEventListener('abort',abort);resolve();});});if(config.network)throw Error('synthetic transport');return {ok:!config.denied,json:async()=>config.badJson?Promise.reject(Error('JSON')):config.tokens??{accessToken:'new-'+number,refreshToken:'refresh-new-'+number}};}
  const bearer=call.headers.get('Authorization');if(bearer?.includes('new-'))return {ok:!config.replayDenied,status:config.replayDenied?401:200,body:init.body};
  if(config.late?.has(url)){const gate=deferred();config.late.set(url,gate);await gate.promise;}
  return{ok:false,status:401};
 };
 const mod={exports:{}};const code=ts.transpileModule(fs.readFileSync(process.env.QA_REFRESH_CONCURRENCY_SOURCE||'apps/web/src/lib/api.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 vm.runInNewContext(code,{module:mod,exports:mod.exports,process:{env:{}},window,Headers,AbortController,CustomEvent,fetch});const api=mod.exports;
 const seed=(workspace,access='old',refresh='refresh-old')=>api.savePortalTokens(workspace,access,refresh);
 const route=workspace=>window.location.pathname=workspace==='AcademyAdmin'?'/portal-accounts':workspace==='Teacher'?'/teacher':workspace==='Portal'?'/portal':'/platform';
 const request=(name,signal)=>api.academyApi('/api/'+name,{method:'POST',body:JSON.stringify({name}),headers:api.apiHeaders(true),signal});
 return{api,seed,route,request,calls,refreshes,storage,window};
}
for(const workspace of ['AcademyAdmin','Teacher','Portal','Platform'])test('one refresh for three simultaneous '+workspace+' requests',async()=>{
 const h=harness();h.seed(workspace);h.route(workspace);const requests=['first','second','third'].map(x=>h.request(x));await tick();const observed=h.refreshes.length;h.refreshes.forEach(x=>x.gate.resolve());const results=await Promise.all(requests);a.equal(observed,1);a.ok(results.every(x=>x.status===200));a.equal(h.calls.length,7);a.deepEqual(results.map(x=>JSON.parse(x.body).name),['first','second','third']);
});
test('late401 reuses completed renewal instead of another refresh or login error',async()=>{const late=new Map([['http://localhost:5092/api/late',null]]),h=harness({late});h.seed('AcademyAdmin');const early=h.request('early'),delayed=h.request('late');await tick();h.refreshes.forEach(x=>x.gate.resolve());a.equal((await early).status,200);late.get('http://localhost:5092/api/late').resolve();const result=await delayed;h.refreshes.forEach(x=>x.gate.resolve());a.equal(result.status,200);a.equal(h.refreshes.length,1);});
for(const cancel of ['first','second'])test('cancel '+cancel+' waiter without cancelling the other',async()=>{const h=harness(),controllers=[new AbortController(),new AbortController()];h.seed('AcademyAdmin');const requests=[h.request('first',controllers[0].signal),h.request('second',controllers[1].signal)];await tick();controllers[cancel==='first'?0:1].abort();await tick();const sharedAborted=h.refreshes[0].call.init.signal.aborted;h.refreshes.forEach(x=>x.gate.resolve());const results=await Promise.all(requests);a.equal(sharedAborted,false);a.equal(h.refreshes.length,1);a.equal(results[cancel==='first'?0:1].status,401);a.equal(results[cancel==='first'?1:0].status,200);});
test('all cancelled waiters abort provider and do not save/replay',async()=>{const h=harness(),controllers=[new AbortController(),new AbortController()];h.seed('AcademyAdmin');const requests=controllers.map((c,i)=>h.request('cancel-'+i,c.signal));await tick();controllers.forEach(x=>x.abort());await tick();h.refreshes.forEach(x=>x.gate.resolve());a.ok((await Promise.all(requests)).every(x=>x.status===401));a.ok(h.refreshes.every(x=>x.call.init.signal.aborted));a.equal(h.storage.get('academydesk.accessToken.AcademyAdmin'),'old');a.equal(h.calls.filter(x=>!x.url.endsWith('/refresh')).length,2);});
for(const config of [{denied:true},{network:true},{badJson:true},{tokens:{}}])test('shared refresh failure leaves all waiters unchanged '+JSON.stringify(config),async()=>{const h=harness(config);h.seed('AcademyAdmin');const requests=[h.request('first'),h.request('second')];await tick();const observed=h.refreshes.length;h.refreshes.forEach(x=>x.gate.resolve());a.ok((await Promise.all(requests)).every(x=>x.status===401));a.equal(observed,1);a.equal(h.storage.get('academydesk.accessToken.AcademyAdmin'),'old');a.equal(h.calls.filter(x=>!x.url.endsWith('/refresh')).length,2);});
test('failed flight cleared so a later manual request can retry',async()=>{const config={denied:true},h=harness(config);h.seed('AcademyAdmin');const one=h.request('first');await tick();h.refreshes[0].gate.resolve();a.equal((await one).status,401);config.denied=false;const two=h.request('second');await tick();a.equal(h.refreshes.length,2);h.refreshes[1].gate.resolve();a.equal((await two).status,200);});
test('separate portal workspaces never share a flight',async()=>{const h=harness();h.seed('AcademyAdmin');h.seed('Teacher','teacher-old','teacher-refresh');h.route('AcademyAdmin');const admin=h.request('admin');h.route('Teacher');const teacher=h.request('teacher');await tick();a.equal(h.refreshes.length,2);a.deepEqual(h.refreshes.map(x=>JSON.parse(x.call.init.body).refreshToken),['refresh-old','teacher-refresh']);h.refreshes.forEach(x=>x.gate.resolve());a.equal((await admin).status,200);a.equal((await teacher).status,200);});
for(const change of ['signout','replacement','same-credentials-signin'])test('shared pending renewal not restored after '+change,async()=>{const h=harness();h.seed('AcademyAdmin');const requests=[h.request('first'),h.request('second')];await tick();h.api.clearPortalTokens('AcademyAdmin');if(change==='replacement')h.seed('AcademyAdmin','different','different-refresh');if(change==='same-credentials-signin')h.seed('AcademyAdmin');h.refreshes.forEach(x=>x.gate.resolve());a.ok((await Promise.all(requests)).every(x=>x.status===401));a.equal(h.storage.get('academydesk.accessToken.AcademyAdmin'),change==='signout'?undefined:change==='replacement'?'different':'old');});
test('old flight completion cannot evict a replacement session flight',async()=>{const h=harness();h.seed('AcademyAdmin');const old=h.request('old');await tick();h.seed('AcademyAdmin','different','different-refresh');const fresh=h.request('fresh');await tick();h.refreshes[0].gate.resolve();a.equal((await old).status,401);const freshTwo=h.request('fresh-two');await tick();const observed=h.refreshes.length;h.refreshes.forEach(x=>x.gate.resolve());a.equal((await fresh).status,200);a.equal((await freshTwo).status,200);a.equal(observed,2);});
test('second401 never creates a refresh loop for any waiter',async()=>{const h=harness({replayDenied:true});h.seed('AcademyAdmin');const requests=[h.request('first'),h.request('second')];await tick();const observed=h.refreshes.length;h.refreshes.forEach(x=>x.gate.resolve());a.ok((await Promise.all(requests)).every(x=>x.status===401));a.equal(observed,1);a.equal(h.calls.filter(x=>!x.url.endsWith('/refresh')).length,4);});
test('cancelled flight can be replaced without old completion deleting the new one',async()=>{const h=harness(),controller=new AbortController();h.seed('AcademyAdmin');const old=h.request('old',controller.signal);await tick();controller.abort();await tick();a.equal((await old).status,401);const fresh=h.request('fresh');await tick();h.refreshes[0].gate.resolve();await tick();const freshTwo=h.request('fresh-two');await tick();const observed=h.refreshes.length;h.refreshes.forEach(x=>x.gate.resolve());a.equal((await fresh).status,200);a.equal((await freshTwo).status,200);a.equal(observed,2);});
