// Actual TSX with controlled hooks/requests/prompts; not browser/device evidence.
const fs=require('node:fs'),assert=require('node:assert/strict'),{test}=require('node:test');
const ts=require('../../apps/web/node_modules/typescript'),jsx=require('../../apps/web/node_modules/react/jsx-runtime');
const code=ts.transpileModule(fs.readFileSync('apps/web/src/app/submission-review/page.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
const nodes=x=>!x||typeof x!=='object'?[]:Array.isArray(x)?x.flatMap(nodes):[x,...nodes(x.props?.children)],text=x=>x==null?'':Array.isArray(x)?x.map(text).join(''):typeof x==='object'?text(x.props?.children):String(x);
const rows=[{id:'one',studentId:'student-one',assignmentId:'work-one',studentName:'Synthetic One',studentNumber:'QA-1',assignmentTitle:'Work One',batchName:'Batch One',submittedAtUtc:'2026-10-01T09:00:00Z',status:'Submitted',responseText:'Identical'}, {id:'two',studentId:'student-two',assignmentId:'work-two',studentName:'Synthetic Two',assignmentTitle:'Work Two',batchName:'Batch Two',submittedAtUtc:'2026-10-01T10:00:00Z',status:'Submitted',responseText:'Identical'}];
async function page(config={}){let i=0,e=0,r=0;const state=[],deps=[],effects=[],refs=[],calls=[],prompts=[],mod={exports:{}};let resolve;
 const react={useState:v=>{const k=i++;if(!(k in state))state[k]=v;return[state[k],v=>state[k]=typeof v==='function'?v(state[k]):v];},useRef:v=>{const k=r++;return refs[k]??= {current:v};},useEffect:(fn,next)=>{const k=e++;if(!deps[k]||next.some((v,j)=>v!==deps[k][j])){deps[k]=next;effects.push(fn);}}};
 const api=async(url,init={})=>{calls.push({url,...init});if(init.method==='PATCH'){if(config.defer)await new Promise(r=>resolve=r);if(config.network)throw Error('offline');const row=(config.rows??rows).find(x=>url.includes('/'+x.id+'/review'));return {ok:!config.saveDenied,json:async()=>config.malformed??{...row,status:'Reviewed',teacherFeedback:JSON.parse(init.body).feedback}};}if(url==='/api/academies')return{ok:true,json:async()=>[{id:'owned'}]};return{ok:!config.loadDenied,json:async()=>config.loadData??config.rows??rows};};
 new Function('require','module','exports','window',code)(n=>n==='react/jsx-runtime'?jsx:n==='react'?react:n==='@/lib/api'?{academyApi:api,apiHeaders:()=>({})}:n==='@/components/workspace-nav'?{WorkspaceNav(){}}:(()=>{throw Error(n);})(),mod,mod.exports,{prompt:message=>{prompts.push(message);return config.cancel?null:'Target feedback';}});
 const render=()=>{i=e=r=0;return mod.exports.default();},flush=async()=>{for(let t=0;t<5;t++){effects.splice(0).forEach(fn=>fn());await new Promise(r=>setImmediate(r));render();}};render();await flush();
 return{render,flush,calls,prompts,click:index=>nodes(render()).filter(x=>x.type==='button')[index].props.onClick(),release:()=>resolve?.(),buttons:()=>nodes(render()).filter(x=>x.type==='button')};}
test('identical responses show learner/assignment/batch/time and uniquely named actions',async()=>{const h=await page();for(const row of rows){for(const value of [row.studentName,row.assignmentTitle,row.batchName,row.studentId,row.assignmentId,row.id])assert.ok(text(h.render()).includes(value),value);assert.ok(h.buttons().some(x=>x.props['aria-label']?.includes(row.studentName)&&x.props['aria-label']?.includes(row.assignmentTitle)&&x.props['aria-label']?.includes(row.id)));}assert.equal(nodes(h.render()).filter(x=>x.type==='time').length,2);assert.equal(h.calls.length,2);});
test('cancelled contextual prompt sends no PATCH',async()=>{const h=await page({cancel:true});await h.click(1);await h.flush();assert.equal(h.calls.filter(x=>x.method==='PATCH').length,0);assert.match(h.prompts[0],/Synthetic Two/);assert.match(h.prompts[0],/Work Two/);assert.match(h.prompts[0],/two/);});
test('confirm updates only exact row and announces success',async()=>{const h=await page();await h.click(1);await h.flush();const patch=h.calls.find(x=>x.method==='PATCH');assert.equal(patch.url,'/api/academies/owned/assignment-submissions/two/review');assert.deepEqual(JSON.parse(patch.body),{feedback:'Target feedback'});assert.equal(h.buttons().length,1);assert.match(text(h.render()),/Review saved/);assert.ok(nodes(h.render()).some(x=>x.props.role==='status'));});
for(const config of [{saveDenied:true},{network:true},{malformed:{}},{malformed:{...rows[0],status:'Reviewed'}},{malformed:{...rows[1],studentId:'other',status:'Reviewed'}}])test('failure retains attribution and review action '+JSON.stringify(config),async()=>{const h=await page(config);await h.click(1);await h.flush();assert.match(text(h.render()),/could not be saved/);assert.equal(h.buttons().length,2);assert.match(text(h.render()),/Synthetic Two/);});
test('pending review blocks duplicate requests until response',async()=>{const h=await page({defer:true});const action=h.buttons()[1].props.onClick;const pending=action();await action();await h.flush();assert.equal(h.calls.filter(x=>x.method==='PATCH').length,1);assert.ok(h.buttons().every(x=>x.props.disabled));h.release();await pending;await h.flush();assert.match(text(h.render()),/Review saved/);});
for(const config of [{loadDenied:true},{loadData:{}},{loadData:[{id:'bad',status:'Submitted'}]}])test('failed or malformed load does not claim empty review queue '+JSON.stringify(config),async()=>{const h=await page(config);assert.match(text(h.render()),/could not be loaded/);assert.doesNotMatch(text(h.render()),/No assignment submissions/);});
test('missing labels and empty responses expose scoped IDs instead of guessed identity',async()=>{const h=await page({rows:[{...rows[0],studentName:null,assignmentTitle:null,batchName:null,responseText:null,submittedAtUtc:'invalid'}]});for(const s of ['student-one','work-one','one','Unavailable','No written response','Submission time unavailable'])assert.ok(text(h.render()).includes(s),s);assert.equal(nodes(h.render()).filter(x=>x.type==='time').length,0);});
test('reviewed row retains nullable feedback and has no Review action',async()=>{const h=await page({rows:[{...rows[0],status:'Reviewed',teacherFeedback:null}]});assert.equal(h.buttons().length,0);assert.match(text(h.render()),/No feedback added/);});
test('SQL UTC timestamp without suffix is not shifted by device timezone',async()=>{const h=await page({rows:[{...rows[0],submittedAtUtc:'2026-10-01T09:00:00'}]});assert.match(text(h.render()),/Submitted: 2026-10-01 09:00:00 UTC/);assert.equal(nodes(h.render()).find(x=>x.type==='time').props.dateTime,'2026-10-01T09:00:00.000Z');});
