// Actual api.ts in an isolated VM. Only synthetic Map storage/controlled fetch; not browser evidence.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
const ts=require('../../apps/web/node_modules/typescript');
function harness(config={}) {
 const file=process.env.QA_SESSION_REFRESH_SOURCE||'apps/web/src/lib/api.ts';
 const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 const calls=[],storage=new Map(),window={location:{pathname:config.path??'/portal-accounts'},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)}};
 let attempt=0;const original={status:config.status??401,ok:false},ok={status:200,ok:true};
 const fetch=async(url,init={})=>{
  calls.push({url,init,headers:new Headers(init.headers)});
  if(url.endsWith('/api/auth/refresh')) {config.onRefresh?.(window,storage);if(config.hold)await config.hold;if(config.refreshNetwork)throw Error('synthetic network');return {ok:!config.refreshDenied,json:async()=>{if(config.badJson)throw Error('synthetic JSON');return config.tokens??{accessToken:'renewed',refreshToken:'renewed-refresh'};}};}
  attempt++;if(attempt===1){config.onRequest?.(window,storage);if(config.requestNetwork)throw Error('synthetic network');return config.success?ok:original;}return config.replayDenied?original:ok;
 };
 const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,process:{env:{}},window,Headers,fetch,AbortController});
 const api=module.exports;const workspace=config.workspace??'AcademyAdmin';
 if(!config.noTokens)api.savePortalTokens(workspace,'old','original-refresh');
 return{api,window,storage,calls,original,ok};
}
for(const [workspace,path] of [['AcademyAdmin','/portal-accounts'],['Teacher','/teacher'],['Portal','/portal'],['Platform','/platform/control']])
 for(const headersKind of ['object','Headers','tuples'])test('renewed authorization wins copied old headers '+workspace+' '+headersKind,async()=>{
  const h=harness({workspace,path});const source=h.api.apiHeaders(true);source['X-Trace']='synthetic';const headers=headersKind==='Headers'?new Headers(source):headersKind==='tuples'?Object.entries(source):source;
  const body=JSON.stringify({synthetic:true}),result=await h.api.academyApi('/api/synthetic',{method:'POST',headers,body,cache:'no-store'});
  assert.equal(result,h.ok);assert.equal(h.calls.length,3);assert.equal(h.calls[0].headers.get('Authorization'),'Bearer old');assert.equal(h.calls[1].headers.get('Authorization'),null);assert.equal(h.calls[2].headers.get('Authorization'),'Bearer renewed');assert.equal(h.calls[2].headers.get('X-Trace'),'synthetic');assert.equal(h.calls[2].headers.get('Content-Type'),'application/json');assert.equal(h.calls[2].init.body,body);assert.equal(h.calls[2].init.method,'POST');assert.equal(h.calls[2].init.cache,'no-store');assert.equal(h.storage.get('academydesk.accessToken.'+workspace),'renewed');assert.equal(source.Authorization,'Bearer old');
 });
test('successful first request never refreshes',async()=>{const h=harness({success:true});assert.equal(await h.api.academyApi('/api/synthetic'),h.ok);assert.equal(h.calls.length,1);});
for(const status of [400,403,409,500])test('HTTP '+status+' never replays',async()=>{const h=harness({status});assert.equal(await h.api.academyApi('/api/synthetic'),h.original);assert.equal(h.calls.length,1);});
for(const config of [{noTokens:true},{refreshDenied:true},{refreshNetwork:true},{badJson:true},{tokens:{}},{tokens:{accessToken:{bad:true}}},{tokens:{accessToken:'  '}},{tokens:{accessToken:'new',refreshToken:{bad:true}}}])test('refresh non-success/malformed leaves original response/storage '+JSON.stringify(config),async()=>{const h=harness(config),before=[...h.storage];assert.equal(await h.api.academyApi('/api/synthetic',{method:'POST',headers:h.api.apiHeaders(true),body:'{}'}),h.original);assert.deepEqual([...h.storage],before);assert.equal(h.calls.filter(x=>!x.url.endsWith('/refresh')).length,1);});
test('refresh endpoint does not recursively refresh',async()=>{const h=harness();await h.api.academyApi('/api/auth/refresh');assert.equal(h.calls.length,1);});
test('second401 returned without a second refresh/replay',async()=>{const h=harness({replayDenied:true});assert.equal(await h.api.academyApi('/api/synthetic'),h.original);assert.equal(h.calls.length,3);});
test('transport loss on initial mutation is not automatically replayed',async()=>{const h=harness({requestNetwork:true});await assert.rejects(h.api.academyApi('/api/synthetic',{method:'POST',body:'{}'}));assert.equal(h.calls.length,1);});
test('legacy administrator keys can renew into workspace keys',async()=>{const h=harness({noTokens:true});h.storage.set('academydesk.accessToken','legacy');h.storage.set('academydesk.refreshToken','legacy-refresh');await h.api.academyApi('/api/synthetic',{headers:h.api.apiHeaders(true)});assert.equal(h.calls[2].headers.get('Authorization'),'Bearer renewed');assert.equal(h.storage.get('academydesk.accessToken.AcademyAdmin'),'renewed');});
test('navigation during original request refreshes only initiating workspace',async()=>{const h=harness({onRequest:w=>w.location.pathname='/teacher'});h.api.savePortalTokens('Teacher','teacher-original','teacher-refresh');await h.api.academyApi('/api/synthetic',{headers:h.api.apiHeaders(true)});assert.deepEqual(JSON.parse(h.calls[1].init.body),{refreshToken:'original-refresh'});assert.equal(h.storage.get('academydesk.accessToken.AcademyAdmin'),'renewed');assert.equal(h.storage.get('academydesk.accessToken.Teacher'),'teacher-original');});
for(const stage of ['onRequest','onRefresh'])for(const change of ['signout','replacement'])test('do not restore/replay a session after '+change+' '+stage,async()=>{const config={[stage]:(_,s)=>{s.delete('academydesk.accessToken.AcademyAdmin');s.delete('academydesk.refreshToken.AcademyAdmin');if(change==='replacement'){s.set('academydesk.accessToken.AcademyAdmin','different-login');s.set('academydesk.refreshToken.AcademyAdmin','different-refresh');}}};const h=harness(config);assert.equal(await h.api.academyApi('/api/synthetic'),h.original);assert.equal(h.calls.filter(x=>!x.url.endsWith('/refresh')).length,1);assert.equal(h.storage.get('academydesk.accessToken.AcademyAdmin'),change==='signout'?undefined:'different-login');});
test('explicit different bearer does not borrow local session refresh',async()=>{const h=harness();await h.api.academyApi('/api/synthetic',{headers:{authorization:'Bearer other', 'X-Trace':'synthetic'}});assert.equal(h.calls.length,1);assert.equal(h.calls[0].headers.get('Authorization'),'Bearer other');});
test('aborting while refresh is pending prevents save/replay',async()=>{const controller=new AbortController(),h=harness({onRefresh:()=>controller.abort()});await h.api.academyApi('/api/synthetic',{signal:controller.signal});assert.equal(h.calls.length,2);assert.equal(h.calls[1].init.signal.aborted,true);assert.equal(h.storage.get('academydesk.accessToken.AcademyAdmin'),'old');});
test('valid access token with omitted optional refresh retains previous refresh',async()=>{const h=harness({tokens:{accessToken:'renewed'}});assert.equal(await h.api.academyApi('/api/synthetic'),h.ok);assert.equal(h.storage.get('academydesk.refreshToken.AcademyAdmin'),'original-refresh');});
