// Actual TSX with controlled hooks; synthetic records only, not SQL/device proof.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const ts=require('../../apps/web/node_modules/typescript'),jsx=require('../../apps/web/node_modules/react/jsx-runtime');
const source=fs.readFileSync('apps/web/src/components/student-admin-profile.tsx','utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
function nodes(n){return Array.isArray(n)?n.flatMap(nodes):!n||typeof n!=='object'?[]:[n,...nodes(n.props?.children)];}
const tick=()=>new Promise(r=>setImmediate(r));
const initial={studentNumber:'SYN-001',preferredName:'Synthetic',gender:'Prefer not to say',dateOfBirth:'2010-01-02',admissionDate:'2026-10-01',addressLine1:'Synthetic address',city:'Synthetic city',state:'Synthetic state',postalCode:'000000',emergencyContactName:'Synthetic contact',emergencyContactPhone:'0000000000',medicalOrAccessibilityNotes:'Synthetic accessibility note',adminNotes:'Synthetic internal note'};
async function fixture(config={}){
 let index=0,refIndex=0,effectIndex=0;const state=new Map(),refs=[],deps=[],effects=[],cleanups=[],calls=[],saved=[],module={exports:{}};
 const react={useState:v=>{const k=index++;if(!state.has(k))state.set(k,v);return[state.get(k),v=>state.set(k,typeof v==='function'?v(state.get(k)):v)];},useRef:v=>{const k=refIndex++;return refs[k]??(refs[k]={current:v});},useEffect:(fn,next)=>{const k=effectIndex++;if(!deps[k]||next.some((v,i)=>v!==deps[k][i])){deps[k]=next;effects.push(fn);}}};
 const api=async(url,init)=>{calls.push({url,...init});assert.equal(url,'/api/academies/owned/students/student/profile');if(config.writeGate)await config.writeGate;if(config.network)throw Error('Synthetic network');return{ok:!config.status,status:config.status||200,json:async()=>{if(config.parseFailure)throw Error('Malformed JSON');return config.payload===undefined?JSON.parse(init.body):config.payload;}};};
 new Function('require','module','exports',code)(n=>n==='react/jsx-runtime'?jsx:n==='react'?react:n==='@/lib/api'?{academyApi:api,apiHeaders:()=>({})}:n==='@/components/design-system/controls'?{StandardSelectField:'select',StandardDateField:'date'}:(()=>{throw Error(n)})(),module,module.exports);
 const wrapper=module.exports.StudentAdminProfile({academyId:'owned',studentId:'student',profile:config.profile||initial,onSaved:value=>{saved.push(value);if(config.callbackFailure)throw Error('Synthetic callback');}});
 const render=()=>{index=refIndex=effectIndex=0;return wrapper.type(wrapper.props);};
 async function settle(){for(let i=0;i<3;i++){for(const fn of effects.splice(0)){const cleanup=fn();if(cleanup)cleanups.push(cleanup);}await tick();render();}}
 render();await settle();const handler=()=>nodes(render()).find(n=>n.type==='button').props.onClick;
 return{state,calls,saved,render,settle,wrapper,other:module.exports.StudentAdminProfile({...wrapper.props,studentId:'other'}),action:async()=>{handler()();await tick();},handler,unmount:()=>cleanups.forEach(fn=>fn())};
}
test('All13 fields and dates retained in exact PUT, durable accessible success',async()=>{const p=await fixture();await p.action();await p.settle();assert.deepEqual(JSON.parse(p.calls[0].body),initial);assert.equal(p.calls[0].method,'PUT');assert.deepEqual(p.saved,[initial]);assert.equal(p.state.get(1),'Administrative profile saved.');assert.equal(p.state.get(2),false);assert.deepEqual(p.state.get(0),initial);assert.equal(nodes(p.render()).find(n=>n.props?.role==='status').props['aria-live'],'polite');});
test('Optional strings remain empty, blank dates become null',async()=>{const p=await fixture({profile:{}});await p.action();const data=JSON.parse(p.calls[0].body);assert.equal(Object.keys(data).length,13);for(const[key,value]of Object.entries(data))assert.equal(value,['dateOfBirth','admissionDate'].includes(key)?null:'');});
for(const status of[400,403,409,500,503])test('HTTP '+status+' retains draft without callback or retry',async()=>{const p=await fixture({status});await p.action();assert.deepEqual(p.state.get(0),initial);assert.equal(p.saved.length,0);assert.equal(p.calls.length,1);assert.equal(p.state.get(2),false);assert.match(p.state.get(1),status>=500?/could not be confirmed.*before retrying/:/could not be saved.*retained/);});
test('Network ambiguity retained, not exposed exception',async()=>{const p=await fixture({network:true});await p.action();assert.match(p.state.get(1),/could not be confirmed/);assert.equal(p.saved.length,0);assert.deepEqual(p.state.get(0),initial);});
for(const config of[{payload:null},{payload:[]},{payload:{}},{payload:{...initial,preferredName:123}},{parseFailure:true},{callbackFailure:true}])test('Confirmed write/malformed display does not invite duplicate '+JSON.stringify(config),async()=>{const p=await fixture(config);await p.action();assert.match(p.state.get(1),/^Administrative profile saved.*could not be displayed.*do not repeat/);assert.deepEqual(p.state.get(0),initial);assert.equal(p.state.get(2),false);assert.equal(p.calls.length,1);if(!config.callbackFailure)assert.equal(p.saved.length,0);});
test('Same-tick stale save and field callback guarded',async()=>{let release;const gate=new Promise(r=>release=r),p=await fixture({writeGate:gate}),handler=p.handler(),field=nodes(p.render()).find(n=>n.type==='input').props.onChange;handler();handler();field({target:{value:'Not accepted while saving'}});try{assert.equal(p.calls.length,1);assert.equal(p.state.get(0).studentNumber,'SYN-001');assert.equal(nodes(p.render()).find(n=>n.type==='fieldset').props.disabled,true);assert.equal(nodes(p.render()).find(n=>n.type==='button').props.disabled,true);}finally{release();}await tick();assert.equal(p.state.get(2),false);});
test('Keyed student scope starts separate editor',async()=>{const p=await fixture();assert.notEqual(p.wrapper.key,p.other.key);assert.deepEqual(JSON.parse(p.wrapper.key),['owned','student']);});
test('Late unmounted write never invokes parent callback',async()=>{let release;const gate=new Promise(r=>release=r),p=await fixture({writeGate:gate}),first=p.action();p.unmount();const snapshot=[...p.state];release();await first;assert.deepEqual([...p.state],snapshot);assert.equal(p.saved.length,0);await p.action();assert.equal(p.calls.length,1);});
test('Same-record parent refresh does not overwrite unsaved draft',async()=>{const p=await fixture();nodes(p.render()).find(n=>n.type==='input').props.onChange({target:{value:'Later draft'}});p.wrapper.props.profile={...initial,studentNumber:'Server snapshot'};await p.settle();assert.equal(p.state.get(0).studentNumber,'Later draft');});
