"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { WorkspaceNav } from "@/components/workspace-nav";
import { academyApi, apiHeaders } from "@/lib/api";
type Academy = { id: string }; type Batch = { id: string; name: string }; type Course = { id: string; name: string; subjectArea?: string }; type Resource = { id: string; title: string; type: string; url: string; batchId?: string; courseId?: string };
export default function Resources() {
  const [academy, setAcademy] = useState<Academy>(); const [batches, setBatches] = useState<Batch[]>([]); const [courses, setCourses] = useState<Course[]>([]); const [resources, setResources] = useState<Resource[]>([]);
  const [title, setTitle] = useState(""); const [url, setUrl] = useState(""); const [type, setType] = useState("Document"); const [course, setCourse] = useState(""); const [batch, setBatch] = useState(""); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState("Loading resources…"); const input = useRef<HTMLInputElement>(null);
  async function load(id?: string) { const academyId = id ?? academy?.id; if (!academyId) return; const [list, batchList, courseList] = await Promise.all([academyApi(`/api/academies/${academyId}/resources`), academyApi(`/api/academies/${academyId}/batches`), academyApi(`/api/academies/${academyId}/courses`)]); if (!list.ok || !batchList.ok || !courseList.ok) throw new Error(); setResources(await list.json()); setBatches(await batchList.json()); setCourses(await courseList.json()); setMessage(""); }
  useEffect(() => { void (async () => { try { const accounts: Academy[] = await (await academyApi("/api/academies")).json(); setAcademy(accounts[0]); await load(accounts[0].id); } catch { setMessage("Resources could not be loaded."); } })(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); if (!academy) return; setMessage("Publishing resource…"); let response: Response; if (file) { const body = new FormData(); body.append("file", file); body.append("title", title); body.append("type", type); if (course) body.append("courseId", course); if (batch) body.append("batchId", batch); response = await academyApi(`/api/academies/${academy.id}/resources/upload`, { method: "POST", body }); } else response = await academyApi(`/api/academies/${academy.id}/resources`, { method: "POST", headers: apiHeaders(true), body: JSON.stringify({ title, description: null, type, url, batchId: batch || null, courseId: course || null, isPublished: true }) }); if (!response.ok) { const result = await response.json().catch(() => null); setMessage(result?.message ?? "Provide a title and a link, or upload a file."); return; } setTitle(""); setUrl(""); setFile(null); if (input.current) input.current.value = ""; await load(); }
  const subject = (id?: string) => courses.find(x => x.id === id)?.name ?? "All subjects"; const audience = (id?: string) => batches.find(x => x.id === id)?.name ?? "All students";
  return <main className="enterprise-settings enterprise-legacy-standard min-h-screen bg-slate-950 text-slate-100"><WorkspaceNav /><div className="mx-auto max-w-6xl px-6 py-10"><p className="text-sm font-semibold uppercase tracking-[.22em] text-cyan-300">Academy library</p><h1 className="mt-3 text-4xl font-semibold">Learning resources</h1><p className="mt-3 text-slate-300">Upload books and PDFs for a subject. Students see only resources for their enrolled subjects.</p>{message && <p className="mt-6 rounded-lg bg-amber-950/40 p-4 text-amber-100">{message}</p>}<section className="mt-8 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={create} className="rounded-2xl bg-slate-900 p-6"><h2 className="text-xl font-semibold">Add subject resource</h2><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Book or PDF title" className="mt-5 w-full rounded-lg bg-slate-950 px-3 py-2" required /><input value={url} disabled={!!file} onChange={e => setUrl(e.target.value)} placeholder="https://… (or upload a file below)" className="mt-3 w-full rounded-lg bg-slate-950 px-3 py-2 disabled:opacity-50" /><input ref={input} type="file" accept=".pdf,.doc,.docx,image/*,audio/*,video/*" onChange={e => { setFile(e.target.files?.[0] ?? null); setUrl(""); }} className="mt-3 block w-full text-sm" /><select value={type} onChange={e => setType(e.target.value)} className="mt-3 w-full rounded-lg bg-slate-950 px-3 py-2"><option>Document</option><option>Book</option><option>SheetMusic</option><option>Audio</option><option>Video</option><option>Link</option></select><select value={course} onChange={e => setCourse(e.target.value)} className="mt-3 w-full rounded-lg bg-slate-950 px-3 py-2"><option value="">All subjects</option>{courses.map(x => <option key={x.id} value={x.id}>{x.name}{x.subjectArea ? ` — ${x.subjectArea}` : ""}</option>)}</select><select value={batch} onChange={e => setBatch(e.target.value)} className="mt-3 w-full rounded-lg bg-slate-950 px-3 py-2"><option value="">All students in the subject</option>{batches.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="mt-5 w-full rounded-lg bg-cyan-400 px-4 py-2 font-semibold text-slate-950">Publish resource</button></form><section className="rounded-2xl bg-slate-900 p-6"><h2 className="text-xl font-semibold">Published library</h2><ul className="mt-4 space-y-3">{resources.map(x => <li key={x.id} className="rounded-lg bg-slate-950 p-4"><a href={x.url} target="_blank" rel="noreferrer" className="font-medium text-cyan-200">{x.title}</a><div className="mt-1 text-sm text-slate-400">{x.type} · {subject(x.courseId)} · {audience(x.batchId)}</div></li>)}</ul></section></section></div></main>;
}
