using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using AcademyDesk.Api.Controllers;
using AcademyDesk.Api.Data;
using AcademyDesk.Api.Domain.Entities;
using AcademyDesk.Api.Tests.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

internal static partial class SqlHarnessEntryPoint
{
    private static async Task VerifyPracticeIdentityAsync(QaApiFactory factory,HttpClient client)
    {
        var baseline=Environment.GetEnvironmentVariable("QA_PRACTICE_BASELINE")=="1";var json=new JsonSerializerOptions(JsonSerializerDefaults.Web);Guid academy,foreign;Student student,foreignStudent;Guid sentinel;
        using(var scope=factory.Services.CreateScope())
        {
            var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();academy=await db.Academies.Where(x=>x.Name=="Synthetic Academy A").Select(x=>x.Id).SingleAsync();foreign=await db.Academies.Where(x=>x.Name=="Synthetic Academy B").Select(x=>x.Id).SingleAsync();
            foreach(var id in new[]{academy,foreign})(await db.Academies.SingleAsync(x=>x.Id==id)).EnabledModulesJson="[\"Core\",\"AcademicGovernance\"]";
            student=new Student{AcademyId=academy,FirstName="Synthetic",LastName="Practice"};foreignStudent=new Student{AcademyId=foreign,FirstName="Private",LastName="Foreign"};var old=new PracticeLog{AcademyId=academy,StudentId=student.Id,PracticeDate=new DateOnly(2020,2,29),MinutesPracticed=5,Status="Reviewed",TeacherFeedback="Preserve reviewed work",ReviewedAtUtc=DateTime.UtcNow};sentinel=old.Id;
            db.AddRange(student,foreignStudent,old,new PracticeLog{AcademyId=foreign,StudentId=foreignStudent.Id,MinutesPracticed=10,Notes="Foreign sentinel"});await db.SaveChangesAsync();
        }
        var token=await LoginAsync(client,"qa-admin-a@example.invalid","Synthetic!39Ab");var foreignToken=await LoginAsync(client,"qa-admin-b@example.invalid","Synthetic!39Ab");var teacherToken=await LoginAsync(client,"qa-teacher-a@example.invalid","Synthetic!39Ab");client.DefaultRequestHeaders.Authorization=null;var route=$"/api/academies/{academy}/practice-logs";var count=0;
        void Pass(string label){count++;Console.WriteLine($"PRACTICEIDENTITY CASE {label} PASS.");}
        async Task<JsonElement> Snapshot(){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();return JsonSerializer.SerializeToElement(new{logs=await db.PracticeLogs.AsNoTracking().OrderBy(x=>x.Id).ToListAsync(),students=await db.Students.AsNoTracking().OrderBy(x=>x.Id).ToListAsync(),audits=await db.AuditLogs.AsNoTracking().OrderBy(x=>x.Id).ToListAsync()});}
        async Task Active(bool active){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();(await db.Students.SingleAsync(x=>x.Id==student.Id)).IsActive=active;await db.SaveChangesAsync();}
        Dictionary<string,object?> Body(string mode="Owned")=>new(){["studentId"]=mode=="Missing"?Guid.NewGuid():mode=="Foreign"?foreignStudent.Id:mode=="Empty"?Guid.Empty:student.Id,["practiceDate"]=mode=="FutureDate"?DateOnly.FromDateTime(DateTime.UtcNow).AddDays(1):new DateOnly(2020,2,29),["minutesPracticed"]=mode=="TooManyMinutes"?1441:mode=="ZeroMinutes"?0:mode=="NegativeMinutes"?-1:30,["focusArea"]=mode=="LongFocus"?new string('x',251):null,["notes"]=mode=="LongNotes"?new string('x',2001):null};
        static void Audit(JsonElement before,JsonElement after,Guid academy,string action)
        {var old=before.GetProperty("audits").EnumerateArray().ToArray();var current=after.GetProperty("audits").EnumerateArray().ToArray();if(current.Length!=old.Length+1||old.Any(x=>!current.Any(y=>JsonElement.DeepEquals(x,y))))throw new InvalidOperationException("Audit preservation differs");var added=current.Single(x=>!old.Any(y=>JsonElement.DeepEquals(x,y)));if(added.GetProperty("AcademyId").GetGuid()!=academy||added.GetProperty("Action").GetString()!=action||added.GetProperty("ActorUserId").ValueKind==JsonValueKind.Null)throw new InvalidOperationException("Actor audit differs");}
        static void Rows(JsonElement before,JsonElement after,int added,Guid? changed=null)
        {var old=before.GetProperty("logs").EnumerateArray().ToArray();var current=after.GetProperty("logs").EnumerateArray().ToArray();if(current.Length!=old.Length+added||old.Where(x=>x.GetProperty("Id").GetGuid()!=changed).Any(x=>!current.Any(y=>JsonElement.DeepEquals(x,y))))throw new InvalidOperationException("Unrelated/foreign work changed");if(!JsonElement.DeepEquals(before.GetProperty("students"),after.GetProperty("students")))throw new InvalidOperationException("Student source changed");}
        static void Same(PracticeLog a,PracticeLog b)
        {if(a.Id!=b.Id||a.AcademyId!=b.AcademyId||a.StudentId!=b.StudentId||a.PracticeDate!=b.PracticeDate||a.MinutesPracticed!=b.MinutesPracticed||a.FocusArea!=b.FocusArea||a.Notes!=b.Notes||a.Status!=b.Status||a.TeacherFeedback!=b.TeacherFeedback||a.ReviewedAtUtc!=b.ReviewedAtUtc||a.CreatedAtUtc!=b.CreatedAtUtc||a.UpdatedAtUtc!=b.UpdatedAtUtc)throw new InvalidOperationException("Complete returned/stored row differs");}
        async Task<Guid> Create(string label,object? body,HttpStatusCode expected,string? auth,bool lifecycleBaseline=false,bool clock=true)
        {
            await Task.Delay(650);var before=await Snapshot();var start=DateTime.UtcNow;using var request=new HttpRequestMessage(HttpMethod.Post,route);if(auth is not null)request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",auth);if(body is not null)request.Content=JsonContent.Create(body);using var response=await client.SendAsync(request);var end=DateTime.UtcNow;if(response.StatusCode!=expected)Console.WriteLine("PRACTICEIDENTITY FAILURE "+label+" body="+await response.Content.ReadAsStringAsync());RequireFinanceStatus(response,expected,label);var after=await Snapshot();
            if(expected!=HttpStatusCode.OK){if(!JsonElement.DeepEquals(before,after))throw new InvalidOperationException("Rejected create wrote rows/audits");Pass(label);return Guid.Empty;}
            var returned=await response.Content.ReadFromJsonAsync<PracticeLog>(json)??throw new InvalidOperationException("Missing create row");using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();var stored=await db.PracticeLogs.AsNoTracking().SingleAsync(x=>x.Id==returned.Id);Same(returned,stored);var input=JsonSerializer.SerializeToElement(body,json);
            if(stored.AcademyId!=academy||stored.StudentId!=input.GetProperty("studentId").GetGuid()||stored.MinutesPracticed!=input.GetProperty("minutesPracticed").GetInt32()||stored.FocusArea!=(input.TryGetProperty("focusArea",out var focus)?focus.GetString():null)||stored.Notes!=(input.TryGetProperty("notes",out var notes)?notes.GetString():null)||input.TryGetProperty("id",out var spoof)&&stored.Id==spoof.GetGuid())throw new InvalidOperationException("Input/identity differs");
            var expectedDate=input.TryGetProperty("practiceDate",out var date)&&date.ValueKind!=JsonValueKind.Null?DateOnly.Parse(date.GetString()!):DateOnly.FromDateTime(start);if(stored.PracticeDate!=expectedDate)throw new InvalidOperationException("Date differs");
            if(lifecycleBaseline){if(stored.Status!="Reviewed"||stored.TeacherFeedback!="Forged"||stored.ReviewedAtUtc?.Year!=2001||stored.CreatedAtUtc.Year!=2001||stored.UpdatedAtUtc?.Year!=2001)throw new InvalidOperationException("Lifecycle baseline not reproduced");}
            else if(clock&&(stored.Status!="Logged"||stored.TeacherFeedback is not null||stored.ReviewedAtUtc is not null||stored.UpdatedAtUtc is not null||stored.CreatedAtUtc<start||stored.CreatedAtUtc>end))throw new InvalidOperationException("Server lifecycle differs");
            Rows(before,after,1);Audit(before,after,academy,"POST PracticeLogs");Pass(label);return stored.Id;
        }
        Dictionary<string,object?> Spoof(Dictionary<string,object?> body){body["id"]=Guid.NewGuid();body["academyId"]=foreign;body["status"]="Reviewed";body["teacherFeedback"]="Forged";body["reviewedAtUtc"]="2001-01-01T00:00:00Z";body["createdAtUtc"]="2001-01-01T00:00:00Z";body["updatedAtUtc"]="2001-01-01T00:00:00Z";return body;}
        if(baseline)
        {foreach(var mode in new[]{"Missing","Foreign","Inactive","TooManyMinutes","FutureDate"}){await Active(mode!="Inactive");await Create("baseline-"+mode,Body(mode),HttpStatusCode.OK,token,clock:false);}await Active(true);await Create("baseline-lifecycle-overpost",Spoof(Body()),HttpStatusCode.OK,token,true);Console.WriteLine($"PRACTICEIDENTITY BASELINE PASS:{count} learner/boundary/lifecycle bypasses reproduced.");return;}
        foreach(var mode in new[]{"Missing","Foreign","Inactive","Empty","NegativeMinutes","ZeroMinutes","TooManyMinutes","FutureDate","LongFocus","LongNotes"}){await Active(mode!="Inactive");await Create("reject-"+mode,Body(mode),HttpStatusCode.BadRequest,token);}await Active(true);
        foreach(var auth in new[]{(label:"anonymous",token:(string?)null,status:HttpStatusCode.Unauthorized),(label:"foreign-actor",token:(string?)foreignToken,status:HttpStatusCode.Forbidden),(label:"teacher",token:(string?)teacherToken,status:HttpStatusCode.Forbidden)})await Create(auth.label+"-denied",Body(),auth.status,auth.token);
        foreach(var body in new object?[]{null,JsonSerializer.SerializeToElement<object?>(null),new{minutesPracticed=30},new{studentId=student.Id},new{studentId="invalid-guid",minutesPracticed=30},new{studentId=student.Id,minutesPracticed="invalid-number"},new{studentId=student.Id,minutesPracticed=30,practiceDate="invalid-date"}})await Create("binding-invalid-"+count,body,body is null?HttpStatusCode.UnsupportedMediaType:HttpStatusCode.BadRequest,token);
        var ids=new List<Guid>();
        foreach(var mode in new[]{"minimum-null","maximum-text","empty-text","whitespace","same-day-repeat","omitted-date","null-date","oldest-date"})
        {var body=Body();body["minutesPracticed"]=mode=="minimum-null"?1:mode=="maximum-text"?1440:30;if(mode=="maximum-text"){body["focusArea"]=new string('x',250);body["notes"]=new string('x',2000);}if(mode=="empty-text"){body["focusArea"]="";body["notes"]="";}if(mode=="whitespace"){body["focusArea"]="  Focus  ";body["notes"]="  Notes  ";}if(mode=="omitted-date")body.Remove("practiceDate");if(mode=="null-date")body["practiceDate"]=null;if(mode=="oldest-date")body["practiceDate"]=DateOnly.MinValue;ids.Add(await Create(mode+"-server-lifecycle",Spoof(body),HttpStatusCode.OK,token));}
        async Task Review(string label,Guid id,string? feedback,string? auth,HttpStatusCode expected)
        {
            await Task.Delay(650);var before=await Snapshot();var start=DateTime.UtcNow;using var request=new HttpRequestMessage(HttpMethod.Patch,route+$"/{id}/review");if(auth is not null)request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",auth);request.Content=JsonContent.Create(new ReviewPracticeLogRequest(feedback));using var response=await client.SendAsync(request);var end=DateTime.UtcNow;RequireFinanceStatus(response,expected,label);var after=await Snapshot();
            if(expected!=HttpStatusCode.OK){if(!JsonElement.DeepEquals(before,after))throw new InvalidOperationException("Rejected review wrote");Pass(label);return;}
            var returned=await response.Content.ReadFromJsonAsync<PracticeLog>(json)??throw new InvalidOperationException("Missing review row");using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();var stored=await db.PracticeLogs.AsNoTracking().SingleAsync(x=>x.Id==id);Same(returned,stored);if(stored.Status!="Reviewed"||stored.TeacherFeedback!=feedback?.Trim()||stored.ReviewedAtUtc is null||stored.ReviewedAtUtc<start||stored.ReviewedAtUtc>end)throw new InvalidOperationException("Review lifecycle differs");Rows(before,after,0,id);Audit(before,after,academy,"PATCH PracticeLogs");var old=before.GetProperty("logs").EnumerateArray().Single(x=>x.GetProperty("Id").GetGuid()==id);var current=after.GetProperty("logs").EnumerateArray().Single(x=>x.GetProperty("Id").GetGuid()==id);foreach(var field in old.EnumerateObject().Where(x=>x.Name is not("Status" or "TeacherFeedback" or "ReviewedAtUtc")))if(!JsonElement.DeepEquals(field.Value,current.GetProperty(field.Name)))throw new InvalidOperationException("Review changed unrelated field");Pass(label);
        }
        await Review("review-trimmed-feedback",ids[0],"  Actual feedback  ",token,HttpStatusCode.OK);await Review("review-null-feedback",ids[1],null,token,HttpStatusCode.OK);await Review("review-empty-feedback",ids[2],"",token,HttpStatusCode.OK);
        Guid foreignId;using(var scope=factory.Services.CreateScope())foreignId=await scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>().PracticeLogs.Where(x=>x.AcademyId==foreign).Select(x=>x.Id).SingleAsync();
        await Review("foreign-row-404",foreignId,"Denied",token,HttpStatusCode.NotFound);await Review("missing-row-404",Guid.NewGuid(),null,token,HttpStatusCode.NotFound);await Review("anonymous-review-denied",ids[0],null,null,HttpStatusCode.Unauthorized);await Review("foreign-actor-review-denied",ids[0],null,foreignToken,HttpStatusCode.Forbidden);await Review("teacher-review-denied",ids[0],null,teacherToken,HttpStatusCode.Forbidden);
        var beforeRead=await Snapshot();using(var request=new HttpRequestMessage(HttpMethod.Get,route)){request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token);using var response=await client.SendAsync(request);RequireFinanceStatus(response,HttpStatusCode.OK,"full-readback");var rows=await response.Content.ReadFromJsonAsync<List<PracticeLog>>(json)??throw new InvalidOperationException("Missing list");using var scope=factory.Services.CreateScope();var expected=await scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>().PracticeLogs.AsNoTracking().Where(x=>x.AcademyId==academy).ToListAsync();if(rows.Count!=9||rows.Count!=expected.Count||!rows.Select(x=>x.PracticeDate).SequenceEqual(rows.Select(x=>x.PracticeDate).OrderDescending()))throw new InvalidOperationException("Scoped count/order differs");foreach(var row in rows)Same(row,expected.Single(x=>x.Id==row.Id));if(rows.Single(x=>x.Id==sentinel).TeacherFeedback!="Preserve reviewed work")throw new InvalidOperationException("Repeated day overwrote reviewed sentinel");}if(!JsonElement.DeepEquals(beforeRead,await Snapshot()))throw new InvalidOperationException("Read wrote");Pass("complete-scoped-ordered-readback-and-repeated-day-preservation");
        Console.WriteLine($"PRACTICEIDENTITY REGRESSION PASS:{count} cases; active scoped learner,minutes/date/text boundaries,server lifecycle,optional/repeated entries,separate exact review,auth/audits/fresh SQL.");
    }
}
