using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using AcademyDesk.Api.Data;
using AcademyDesk.Api.Domain.Entities;
using AcademyDesk.Api.Tests.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

internal static partial class SqlHarnessEntryPoint
{
    private static async Task VerifySubmissionIdentityAsync(QaApiFactory factory,HttpClient client)
    {
        var baseline=Environment.GetEnvironmentVariable("QA_SUBMISSION_BASELINE")=="1";var json=new JsonSerializerOptions(JsonSerializerDefaults.Web);Guid academy,foreign;Student student,other,foreignStudent;Batch batch,foreignBatch;Assignment assignment;Enrollment enrollment;
        using(var scope=factory.Services.CreateScope())
        {
            var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();academy=await db.Academies.Where(x=>x.Name=="Synthetic Academy A").Select(x=>x.Id).SingleAsync();foreign=await db.Academies.Where(x=>x.Name=="Synthetic Academy B").Select(x=>x.Id).SingleAsync();
            foreach(var id in new[]{academy,foreign})(await db.Academies.SingleAsync(x=>x.Id==id)).EnabledModulesJson="[\"Core\",\"AcademicGovernance\"]";
            batch=await db.Batches.SingleAsync(x=>x.AcademyId==academy);foreignBatch=new Batch{AcademyId=foreign,Name="Synthetic foreign batch"};
            student=new Student{AcademyId=academy,FirstName="Synthetic",LastName="Submission"};other=new Student{AcademyId=academy,FirstName="Synthetic",LastName="Other"};foreignStudent=new Student{AcademyId=foreign,FirstName="Private",LastName="Foreign"};
            assignment=new Assignment{AcademyId=academy,BatchId=batch.Id,Title="Synthetic submission work",IsPublished=true};enrollment=new Enrollment{AcademyId=academy,StudentId=student.Id,BatchId=batch.Id};
            db.AddRange(student,other,foreignStudent,foreignBatch,assignment,enrollment);db.Add(new AssignmentSubmission{AcademyId=foreign,StudentId=foreignStudent.Id,AssignmentId=Guid.NewGuid(),ResponseText="Foreign sentinel",Status="Reviewed",TeacherFeedback="Preserve"});await db.SaveChangesAsync();
        }
        var token=await LoginAsync(client,"qa-admin-a@example.invalid","Synthetic!39Ab");var foreignToken=await LoginAsync(client,"qa-admin-b@example.invalid","Synthetic!39Ab");var teacherToken=await LoginAsync(client,"qa-teacher-a@example.invalid","Synthetic!39Ab");client.DefaultRequestHeaders.Authorization=null;
        var count=0;void Pass(string label){count++;Console.WriteLine($"SUBMISSIONIDENTITY CASE {label} PASS.");}string route=$"/api/academies/{academy}/assignment-submissions";
        async Task<JsonElement> Snapshot(){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();return JsonSerializer.SerializeToElement(new{rows=await db.AssignmentSubmissions.AsNoTracking().OrderBy(x=>x.Id).ToListAsync(),students=await db.Students.AsNoTracking().OrderBy(x=>x.Id).ToListAsync(),assignments=await db.Assignments.AsNoTracking().OrderBy(x=>x.Id).ToListAsync(),batches=await db.Batches.AsNoTracking().OrderBy(x=>x.Id).ToListAsync(),enrollments=await db.Enrollments.AsNoTracking().OrderBy(x=>x.Id).ToListAsync(),audits=await db.AuditLogs.AsNoTracking().OrderBy(x=>x.Id).ToListAsync()});}
        async Task Configure(string mode)
        {
            using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();var a=await db.Assignments.SingleAsync(x=>x.Id==assignment.Id);a.IsPublished=mode!="Unpublished";a.StudentId=mode=="WrongPrivateStudent"?other.Id:mode=="PrivateTarget"?student.Id:null;a.AcademyId=mode=="ForeignAssignment"?foreign:academy;a.BatchId=mode=="ForeignBatch"?foreignBatch.Id:mode=="MissingBatch"?Guid.NewGuid():batch.Id;
            var e=await db.Enrollments.SingleAsync(x=>x.Id==enrollment.Id);e.AcademyId=mode=="ForeignEnrollment"?foreign:academy;e.BatchId=mode=="WrongBatch"?foreignBatch.Id:batch.Id;e.Status=mode=="InactiveEnrollment"?"Withdrawn":"Active";e.StudentId=mode=="NoEnrollment"?other.Id:student.Id;
            await db.SaveChangesAsync();
        }
        Dictionary<string,object?> Body(string mode,string? response="Synthetic response")=>new(){["assignmentId"]=mode=="MissingAssignment"?Guid.NewGuid():mode=="EmptyAssignment"?Guid.Empty:assignment.Id,["studentId"]=mode=="MissingStudent"?Guid.NewGuid():mode=="ForeignStudent"?foreignStudent.Id:mode=="EmptyStudent"?Guid.Empty:student.Id,["responseText"]=mode=="TooLong"?new string('x',4001):response};
        void SourcesSame(JsonElement before,JsonElement after){foreach(var field in before.EnumerateObject().Where(x=>x.Name!="rows"&&x.Name!="audits"))if(!JsonElement.DeepEquals(field.Value,after.GetProperty(field.Name)))throw new InvalidOperationException("Unexpected source write "+field.Name);}
        async Task<Guid> Create(string label,object? body,HttpStatusCode expected,string? auth,bool baselineLifecycle=false,bool verifyClock=true)
        {
            await Task.Delay(650);var before=await Snapshot();var start=DateTime.UtcNow;using var request=new HttpRequestMessage(HttpMethod.Post,route);if(auth is not null)request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",auth);if(body is not null)request.Content=JsonContent.Create(body);using var response=await client.SendAsync(request);var end=DateTime.UtcNow;if(response.StatusCode!=expected)Console.WriteLine("SUBMISSIONIDENTITY FAILURE "+label+" body="+await response.Content.ReadAsStringAsync());RequireFinanceStatus(response,expected,label);var after=await Snapshot();
            if(expected!=HttpStatusCode.OK){if(!JsonElement.DeepEquals(before,after))throw new InvalidOperationException("Rejected create changed data/audits "+label);Pass(label);return Guid.Empty;}
            var returned=await response.Content.ReadFromJsonAsync<AssignmentSubmission>(json)??throw new InvalidOperationException("Missing submission body");using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();var stored=await db.AssignmentSubmissions.AsNoTracking().SingleAsync(x=>x.Id==returned.Id);
            // SQL DateTime readbacks omit Kind; compare each semantic value, not date suffix spelling.
            if(returned.Id!=stored.Id||returned.AcademyId!=academy||returned.AcademyId!=stored.AcademyId||returned.StudentId!=stored.StudentId||returned.AssignmentId!=stored.AssignmentId||returned.Status!=stored.Status||returned.ResponseText!=stored.ResponseText||returned.TeacherFeedback!=stored.TeacherFeedback||returned.SubmittedAtUtc!=stored.SubmittedAtUtc||returned.CreatedAtUtc!=stored.CreatedAtUtc||returned.UpdatedAtUtc!=stored.UpdatedAtUtc)throw new InvalidOperationException("Complete returned/stored contract differs");
            if(baselineLifecycle){if(stored.Status!="Reviewed"||stored.TeacherFeedback!="Forged feedback"||stored.SubmittedAtUtc.Year!=2001||stored.CreatedAtUtc.Year!=2001||stored.UpdatedAtUtc?.Year!=2001)throw new InvalidOperationException("Baseline lifecycle bypass not reproduced");}
            else if(verifyClock&&(stored.Status!="Submitted"||stored.TeacherFeedback is not null||stored.UpdatedAtUtc is not null||stored.SubmittedAtUtc<start||stored.SubmittedAtUtc>end||stored.CreatedAtUtc<start||stored.CreatedAtUtc>end))throw new InvalidOperationException("Server lifecycle differs");
            var requestJson=JsonSerializer.SerializeToElement(body,json);if(stored.AssignmentId!=requestJson.GetProperty("assignmentId").GetGuid()||stored.StudentId!=requestJson.GetProperty("studentId").GetGuid()||stored.ResponseText!=requestJson.GetProperty("responseText").GetString()||requestJson.TryGetProperty("id",out var spoof)&&stored.Id==spoof.GetGuid())throw new InvalidOperationException("Submission input/ID differs");
            SourcesSame(before,after);var oldRows=before.GetProperty("rows").EnumerateArray().ToArray();var current=after.GetProperty("rows").EnumerateArray().ToArray();if(current.Length!=oldRows.Length+1||oldRows.Any(x=>!current.Any(y=>JsonElement.DeepEquals(x,y))))throw new InvalidOperationException("Unrelated/foreign row changed");var oldAudits=before.GetProperty("audits").EnumerateArray().ToArray();var audits=after.GetProperty("audits").EnumerateArray().ToArray();if(audits.Length!=oldAudits.Length+1||oldAudits.Any(x=>!audits.Any(y=>JsonElement.DeepEquals(x,y))))throw new InvalidOperationException("Audit mismatch");var audit=audits.Single(x=>!oldAudits.Any(y=>JsonElement.DeepEquals(x,y)));if(audit.GetProperty("AcademyId").GetGuid()!=academy||audit.GetProperty("Action").GetString()!="POST AssignmentSubmissions"||audit.GetProperty("ActorUserId").ValueKind==JsonValueKind.Null)throw new InvalidOperationException("Create actor audit mismatch");Pass(label);return stored.Id;
        }
        if(baseline)
        {
            foreach(var mode in new[]{"MissingStudent","ForeignStudent","WrongBatch","WrongPrivateStudent","Unpublished"}){await Configure(mode);await Create("baseline-"+mode,Body(mode),HttpStatusCode.OK,token,verifyClock:false);using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();db.AssignmentSubmissions.RemoveRange(await db.AssignmentSubmissions.Where(x=>x.AcademyId==academy).ToListAsync());await db.SaveChangesAsync();}
            await Configure("Owned");var forged=Body("Owned");forged["id"]=Guid.NewGuid();forged["academyId"]=foreign;forged["status"]="Reviewed";forged["teacherFeedback"]="Forged feedback";forged["submittedAtUtc"]="2001-01-01T00:00:00Z";forged["createdAtUtc"]="2001-01-01T00:00:00Z";forged["updatedAtUtc"]="2001-01-01T00:00:00Z";await Create("baseline-lifecycle-overpost",forged,HttpStatusCode.OK,token,true);
            Console.WriteLine($"SUBMISSIONIDENTITY BASELINE PASS:{count} administrative identity/lifecycle bypasses reproduced.");return;
        }
        foreach(var mode in new[]{"MissingStudent","ForeignStudent","EmptyStudent","MissingAssignment","ForeignAssignment","EmptyAssignment","Unpublished","WrongPrivateStudent","NoEnrollment","WrongBatch","ForeignEnrollment","InactiveEnrollment","ForeignBatch","MissingBatch","TooLong"}){await Configure(mode);await Create("reject-"+mode,Body(mode),HttpStatusCode.BadRequest,token);}
        await Configure("Owned");await Create("anonymous-denied",Body("Owned"),HttpStatusCode.Unauthorized,null);await Create("foreign-actor-denied",Body("Owned"),HttpStatusCode.Forbidden,foreignToken);await Create("teacher-denied",Body("Owned"),HttpStatusCode.Forbidden,teacherToken);
        foreach(var invalid in new object?[]{null,JsonSerializer.SerializeToElement<object?>(null),new{studentId=student.Id},new{assignmentId=assignment.Id},new{assignmentId="not-a-guid",studentId=student.Id},new{assignmentId=assignment.Id,studentId=student.Id,responseText=42}})await Create("binding-invalid-"+count,invalid,invalid is null?HttpStatusCode.UnsupportedMediaType:HttpStatusCode.BadRequest,token);
        foreach(var scenario in new[]{(label:"null-response",text:(string?)null),(label:"empty-response",text:(string?)""),(label:"max-response",text:(string?)new string('x',4000)),(label:"private-target",text:(string?)"Private response")})
        {
            await Configure(scenario.label=="private-target"?"PrivateTarget":"Owned");var body=Body("Owned",scenario.text);body["id"]=Guid.NewGuid();body["academyId"]=foreign;body["status"]="Reviewed";body["teacherFeedback"]="Forged feedback";body["submittedAtUtc"]="2001-01-01T00:00:00Z";body["createdAtUtc"]="2001-01-01T00:00:00Z";body["updatedAtUtc"]="2001-01-01T00:00:00Z";var id=await Create(scenario.label+"-server-lifecycle",body,HttpStatusCode.OK,token);await Create(scenario.label+"-duplicate-no-write",Body("Owned","Replacement"),HttpStatusCode.Conflict,token);
            // New assignment/student key for the next accepted case; do not delete created regression rows.
            using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();var fresh=new Assignment{AcademyId=academy,BatchId=batch.Id,Title="Synthetic next work "+count,IsPublished=true};db.Add(fresh);await db.SaveChangesAsync();assignment=fresh;
        }
        var snapshot=await Snapshot();using(var read=new HttpRequestMessage(HttpMethod.Get,route)){read.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token);using var response=await client.SendAsync(read);RequireFinanceStatus(response,HttpStatusCode.OK,"full-readback");var rows=await response.Content.ReadFromJsonAsync<JsonElement>(json);if(rows.GetArrayLength()!=4||rows.EnumerateArray().Any(x=>x.GetProperty("studentName").GetString()!="Synthetic Submission"||x.GetProperty("teacherFeedback").ValueKind!=JsonValueKind.Null||x.GetProperty("status").GetString()!="Submitted"))throw new InvalidOperationException("Contextual readback differs");}if(!JsonElement.DeepEquals(snapshot,await Snapshot()))throw new InvalidOperationException("Readback wrote");Pass("full-contextual-readback-no-write");
        await Configure("Owned");var concurrentBefore=await Snapshot();
        async Task<(HttpStatusCode Status,AssignmentSubmission? Row)> ConcurrentCreate()
        {using var request=new HttpRequestMessage(HttpMethod.Post,route);request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token);request.Content=JsonContent.Create(Body("Owned","Concurrent synthetic response"));using var response=await client.SendAsync(request);return(response.StatusCode,response.StatusCode==HttpStatusCode.OK?await response.Content.ReadFromJsonAsync<AssignmentSubmission>(json):null);}
        var pair=await Task.WhenAll(ConcurrentCreate(),ConcurrentCreate());if(pair.Count(x=>x.Status==HttpStatusCode.OK)!=1||pair.Count(x=>x.Status==HttpStatusCode.Conflict)!=1)throw new InvalidOperationException("Concurrent creates did not return one200/one409");
        var concurrentAfter=await Snapshot();SourcesSame(concurrentBefore,concurrentAfter);
        foreach(var field in new[]{"rows","audits"}){var original=concurrentBefore.GetProperty(field).EnumerateArray().ToArray();var current=concurrentAfter.GetProperty(field).EnumerateArray().ToArray();if(current.Length!=original.Length+1||original.Any(x=>!current.Any(y=>JsonElement.DeepEquals(x,y))))throw new InvalidOperationException("Concurrent create changed unrelated rows/audits");}
        using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<AcademyDeskDbContext>();var saved=await db.AssignmentSubmissions.AsNoTracking().SingleAsync(x=>x.AcademyId==academy&&x.AssignmentId==assignment.Id&&x.StudentId==student.Id);var returned=pair.Single(x=>x.Status==HttpStatusCode.OK).Row!;if(saved.Id!=returned.Id||saved.Status!="Submitted"||saved.ResponseText!="Concurrent synthetic response"||saved.TeacherFeedback is not null)throw new InvalidOperationException("Concurrent winner differs");}
        Pass("simultaneous-pair-one-create-one-conflict-exact-SQL-audit");
        Console.WriteLine($"SUBMISSIONIDENTITY REGRESSION PASS:{count} cases; real scoped eligibility/server lifecycle/duplicate conflicts/shape and access no-write/actor audit/fresh SQL/contextual readback.");
    }
}
