"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Academy = { id: string; name: string };
type Course = { id: string; name: string; academyType: string; level?: string | null; description?: string | null };
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5092";

export default function CoursesPage() {
  const [academies, setAcademies] = useState<Academy[]>([]); const [academyId, setAcademyId] = useState(""); const [courses, setCourses] = useState<Course[]>([]); const [name, setName] = useState(""); const [type, setType] = useState("Music"); const [level, setLevel] = useState(""); const [message, setMessage] = useState("");
  async function loadAcademies() { const r = await fetch(`${apiUrl}/api/academies`, { cache: "no-store" }); if (!r.ok) throw new Error(); const data: Academy[] = await r.json(); setAcademies(data); if (!academyId && data.length) setAcademyId(data[0].id); }
  async function loadCourses(id: string) { if (!id) return setCourses([]); const r = await fetch(`${apiUrl}/api/academies/${id}/courses`, { cache: "no-store" }); if (!r.ok) throw new Error(); setCourses(await r.json()); }
  useEffect(() => { void loadAcademies().catch(() => setMessage("The AcademyDesk API is not reachable.")); }, []); useEffect(() => { void loadCourses(academyId).catch(() => setMessage("Courses could not be loaded.")); }, [academyId]);
  async function createCourse(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const r = await fetch(`${apiUrl}/api/academies/${academyId}/courses`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, academyType: type, level }) }); if (!r.ok) return setMessage("The course could not be saved."); setName(""); setLevel(""); setMessage(""); await loadCourses(academyId); }
  return <main className="min-h-screen bg-slate-950 px-6 py-12 text-slate-100"><div className="mx-auto max-w-5xl"><Link href="/" className="text-sm text-cyan-300">← Academy setup</Link><h1 className="mt-4 text-4xl font-semibold">Course catalogue</h1><p className="mt-3 text-slate-300">Configure music programs, tuition subjects, and coaching courses in one catalogue.</p>{message && <p className="mt-5 rounded-lg border border-amber-700/50 bg-amber-950/40 p-3 text-sm text-amber-200">{message}</p>}{academies.length === 0 ? <p className="mt-8 rounded-lg border border-dashed border-slate-700 p-8 text-center text-slate-400">Create an academy first.</p> : <><label className="mt-8 block text-sm text-slate-300" htmlFor="academy">Academy</label><select id="academy" value={academyId} onChange={(e) => setAcademyId(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2">{academies.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><section className="mt-6 grid gap-6 md:grid-cols-2"><form onSubmit={createCourse} className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Add course</h2><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Course or subject name" className="mt-5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" required /><select value={type} onChange={(e) => setType(e.target.value)} className="mt-3 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"><option>Music</option><option>Tuition</option><option>Coaching</option></select><input value={level} onChange={(e) => setLevel(e.target.value)} placeholder="Level (optional)" className="mt-3 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" /><button className="mt-5 w-full rounded-lg bg-cyan-400 px-4 py-2.5 font-semibold text-slate-950 hover:bg-cyan-300">Create course</button></form><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Courses</h2>{courses.length === 0 ? <p className="mt-6 text-slate-400">No courses yet.</p> : <ul className="mt-4 space-y-3">{courses.map((c) => <li key={c.id} className="rounded-lg border border-slate-700 p-4"><div className="font-medium">{c.name}</div><div className="mt-1 text-sm text-slate-400">{c.academyType}{c.level ? ` · ${c.level}` : ""}</div></li>)}</ul>}</section></section></>}</div></main>;
}
