"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5092";

export default function RegisterPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function register(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (password !== confirm) return setMessage("Passwords do not match."); setBusy(true); setMessage(""); try { const response = await fetch(`${apiUrl}/api/auth/register`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!response.ok) { const detail = await response.text(); throw new Error(detail); } setMessage("Account created. You can now sign in."); setPassword(""); setConfirm(""); } catch { setMessage("Registration failed. Use a valid email and a password that meets the requirements."); } finally { setBusy(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-slate-950 px-6 text-slate-100"><form onSubmit={register} className="w-full max-w-md rounded-2xl border border-slate-800 bg-slate-900 p-7 shadow-xl"><Link href="/login" className="text-sm text-cyan-300">← Sign in</Link><h1 className="mt-6 text-3xl font-semibold">Create owner account</h1><p className="mt-2 text-slate-400">This account will be used to set up your AcademyDesk workspace.</p><label className="mt-7 block text-sm text-slate-300" htmlFor="email">Email</label><input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" required /><label className="mt-4 block text-sm text-slate-300" htmlFor="password">Password</label><input id="password" type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" required /><label className="mt-4 block text-sm text-slate-300" htmlFor="confirm">Confirm password</label><input id="confirm" type="password" minLength={8} value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" required /><button disabled={busy} className="mt-6 w-full rounded-lg bg-cyan-400 px-4 py-2.5 font-semibold text-slate-950 hover:bg-cyan-300 disabled:opacity-60">{busy ? "Creating…" : "Create account"}</button>{message && <p className="mt-4 rounded-lg border border-slate-700 p-3 text-sm text-slate-300">{message}</p>}</form></main>;
}
