"use client";
import { FormEvent, useEffect, useState } from "react";
import { WorkspaceNav } from "@/components/workspace-nav";
import { academyApi, apiHeaders } from "@/lib/api";
import { MeetingProviderDraft, MeetingProviderSettings } from "@/components/meeting-provider-settings";

type Academy = { id: string };
type ChannelName = "Email" | "WhatsApp" | "Meeting";
type Channel = { channel: ChannelName; provider: string; status: string; senderName?: string; senderAddress?: string; phoneNumber?: string; externalAccountReference?: string; messagesEnabled: boolean; hasSecureConnection: boolean };
type Draft = { provider: string; status: string; senderName: string; senderAddress: string; phoneNumber: string; externalAccountReference: string; messagesEnabled: boolean };
const fresh = (provider: string): Draft => ({ provider, status: "NotConfigured", senderName: "", senderAddress: "", phoneNumber: "", externalAccountReference: "", messagesEnabled: false });
const meetingBlank: MeetingProviderDraft = { provider: "GoogleWorkspace", status: "NotConfigured", organizerName: "", organizerEmail: "", reference: "" };

export default function CommunicationSettingsPage() {
  const [academy, setAcademy] = useState<Academy>(); const [items, setItems] = useState<Channel[]>([]); const [email, setEmail] = useState(fresh("GoogleWorkspace")); const [whatsApp, setWhatsApp] = useState(fresh("MetaCloudApi")); const [meeting, setMeeting] = useState(meetingBlank); const [message, setMessage] = useState("Loading channel settings…");
  async function load(id?: string) { const academyId = id ?? academy?.id; if (!academyId) return; const response = await academyApi(`/api/academies/${academyId}/communication-settings`, { cache: "no-store" }); if (!response.ok) throw new Error(); const rows: Channel[] = await response.json(); setItems(rows); const emailRow = rows.find((x) => x.channel === "Email"); const whatsAppRow = rows.find((x) => x.channel === "WhatsApp"); const meetingRow = rows.find((x) => x.channel === "Meeting"); if (emailRow) setEmail({ provider: emailRow.provider, status: emailRow.status, senderName: emailRow.senderName ?? "", senderAddress: emailRow.senderAddress ?? "", phoneNumber: "", externalAccountReference: "", messagesEnabled: emailRow.messagesEnabled }); if (whatsAppRow) setWhatsApp({ provider: whatsAppRow.provider, status: whatsAppRow.status, senderName: whatsAppRow.senderName ?? "", senderAddress: "", phoneNumber: whatsAppRow.phoneNumber ?? "", externalAccountReference: whatsAppRow.externalAccountReference ?? "", messagesEnabled: whatsAppRow.messagesEnabled }); if (meetingRow) setMeeting({ provider: meetingRow.provider, status: meetingRow.status, organizerName: meetingRow.senderName ?? "", organizerEmail: meetingRow.senderAddress ?? "", reference: meetingRow.externalAccountReference ?? "" }); setMessage(""); }
  useEffect(() => { void (async () => { try { const response = await academyApi("/api/academies", { cache: "no-store" }); const academies: Academy[] = await response.json(); if (!response.ok || !academies[0]) throw new Error(); setAcademy(academies[0]); await load(academies[0].id); } catch { setMessage("Settings could not be loaded. Confirm the API is running on port 5092."); } })(); }, []);
  async function save(channel: ChannelName, draft: Draft) { if (!academy) return; const response = await academyApi(`/api/academies/${academy.id}/communication-settings/${channel}`, { method: "PUT", headers: apiHeaders(true), body: JSON.stringify({ ...draft, replyToAddress: null }) }); const result = await response.json().catch(() => null); if (!response.ok) return setMessage(result?.message ?? "Settings could not be saved."); setMessage(`${channel} settings saved.`); await load(); }
  async function saveMeeting() { if (!academy) return; const response = await academyApi(`/api/academies/${academy.id}/communication-settings/Meeting`, { method: "PUT", headers: apiHeaders(true), body: JSON.stringify({ provider: meeting.provider, status: meeting.status, senderName: meeting.organizerName, senderAddress: meeting.organizerEmail, replyToAddress: null, phoneNumber: null, externalAccountReference: meeting.reference, messagesEnabled: false }) }); const result = await response.json().catch(() => null); if (!response.ok) return setMessage(result?.message ?? "Meeting provider settings could not be saved."); setMessage("Meeting provider settings saved. Secure OAuth connection is the next step."); await load(); }
  const fields = "w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2";
  const senderForm = (channel: "Email" | "WhatsApp", draft: Draft, setDraft: (draft: Draft) => void) => <form onSubmit={(event: FormEvent) => { event.preventDefault(); void save(channel, draft); }} className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">{channel === "Email" ? "Email sender" : "WhatsApp sender"}</h2><div className="mt-5 grid gap-3"><select value={draft.provider} onChange={(event) => setDraft({ ...draft, provider: event.target.value })} className={fields}>{channel === "Email" ? <><option value="GoogleWorkspace">Google Workspace</option><option value="Microsoft365">Microsoft 365</option><option value="SMTP">Custom SMTP</option></> : <><option value="MetaCloudApi">Meta WhatsApp Cloud API</option><option value="BSP">Business solution provider</option></>}</select><input value={draft.senderName} onChange={(event) => setDraft({ ...draft, senderName: event.target.value })} placeholder="Display name" className={fields} />{channel === "Email" ? <input type="email" value={draft.senderAddress} onChange={(event) => setDraft({ ...draft, senderAddress: event.target.value })} placeholder="Sender email" className={fields} /> : <input value={draft.phoneNumber} onChange={(event) => setDraft({ ...draft, phoneNumber: event.target.value })} placeholder="Dedicated WhatsApp number" className={fields} />}</div><button disabled={!academy} className="mt-5 w-full rounded-lg bg-cyan-400 px-4 py-2.5 font-semibold text-slate-950 disabled:opacity-60">Save {channel.toLowerCase()} settings</button></form>;
  return <main className="enterprise-settings enterprise-legacy-standard min-h-screen bg-slate-950 text-slate-100"><WorkspaceNav /><div className="mx-auto max-w-6xl px-6 py-10"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-cyan-300">Engagement</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Channel settings</h1><p className="mt-3 max-w-3xl text-slate-300">Configure academy communication channels and the provider that creates online class meetings.</p>{message && <p className="mt-6 rounded-lg border border-amber-700/50 bg-amber-950/40 p-4 text-sm text-amber-100">{message}</p>}<div className="mt-8 grid gap-6 lg:grid-cols-2">{senderForm("Email", email, setEmail)}{senderForm("WhatsApp", whatsApp, setWhatsApp)}<MeetingProviderSettings value={meeting} onChange={setMeeting} onSave={() => void saveMeeting()} disabled={!academy} /></div><section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Secure connection</h2><p className="mt-2 text-sm text-slate-300">{items.some((item) => item.hasSecureConnection) ? "A secure provider connection is recorded." : "Save the provider information first. OAuth client secrets and access tokens are connected securely in the next step."}</p></section></div></main>;
}
