"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { WorkspaceNav } from "@/components/workspace-nav";
import { academyApi, apiHeaders } from "@/lib/api";

type Academy = { id: string }; type Person = { id: string; firstName: string; lastName: string; email?: string | null; phone?: string | null }; type Preference = { recipientId: string; recipientType: string; emailAllowed: boolean; whatsAppAllowed: boolean; marketingAllowed: boolean; notes?: string | null };
export default function CommunicationPreferencesPage() { const [academy, setAcademy] = useState<Academy>(); const [students, setStudents] = useState<Person[]>([]); const [guardians, setGuardians] = useState<Person[]>([]); const [preferences, setPreferences] = useState<Preference[]>([]); const [recipientType, setRecipientType] = useState("Guardian"); const [recipientId, setRecipientId] = useState(""); const [emailAllowed, setEmailAllowed] = useState(false); const [whatsAppAllowed, setWhatsAppAllowed] = useState(false); const [marketingAllowed, setMarketingAllowed] = useState(false); const [notes, setNotes] = useState(""); const [message, setMessage] = useState("Loading contact preferences…"); const [saveConfirmation, setSaveConfirmation] = useState("");
  async function load(id?: string) { const academyId = id ?? academy?.id; if (!academyId) return; const [studentResponse, guardianResponse, preferenceResponse] = await Promise.all([academyApi(`/api/academies/${academyId}/students`, { cache: "no-store" }), academyApi(`/api/academies/${academyId}/guardians`, { cache: "no-store" }), academyApi(`/api/academies/${academyId}/communication-preferences`, { cache: "no-store" })]); if (![studentResponse, guardianResponse, preferenceResponse].every(x => x.ok)) throw new Error(); setStudents(await studentResponse.json()); setGuardians(await guardianResponse.json()); setPreferences(await preferenceResponse.json()); setMessage(""); }
  useEffect(() => { async function initialise() { try { const response = await academyApi("/api/academies", { cache: "no-store" }); if (response.status === 401) return setMessage("Please sign in as an academy owner or manager first."); const academies: Academy[] = await response.json(); if (!academies[0]) return setMessage("Create your academy first."); setAcademy(academies[0]); await load(academies[0].id); } catch { setMessage("Preferences could not be loaded. Confirm the API is running on port 5092."); } } void initialise(); }, []);
  const people = recipientType === "Guardian" ? guardians : students; const selected = useMemo(() => preferences.find(x => x.recipientType === recipientType && x.recipientId === recipientId), [preferences, recipientType, recipientId]);
  useEffect(() => { setEmailAllowed(selected?.emailAllowed ?? false); setWhatsAppAllowed(selected?.whatsAppAllowed ?? false); setMarketingAllowed(selected?.marketingAllowed ?? false); setNotes(selected?.notes ?? ""); }, [selected]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!academy || !recipientId) return; setMessage("Saving consent preferences…"); setSaveConfirmation(""); try { const response = await academyApi(`/api/academies/${academy.id}/communication-preferences/${recipientType}/${recipientId}`, { method: "PUT", headers: apiHeaders(true), body: JSON.stringify({ emailAllowed, whatsAppAllowed, marketingAllowed, notes }) }); const result = await response.json().catch(() => null); if (!response.ok) return setMessage(result?.message ?? "Preference could not be saved."); await load(); const person = people.find(item => item.id === recipientId); setMessage(""); setSaveConfirmation(`${recipientType} preferences saved for ${person ? `${person.firstName} ${person.lastName}` : "the selected contact"}.`); } catch { setMessage("Preferences were saved, but the updated list could not be refreshed. Refresh this page and check again."); } }
  const field = "w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2";
  return <main className="enterprise-settings enterprise-legacy-standard min-h-screen bg-slate-950 text-slate-100"><WorkspaceNav /><div className="mx-auto max-w-4xl px-6 py-10"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-cyan-300">Communication</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Contact preferences</h1><p className="mt-3 text-slate-300">Record each student’s or guardian’s communication consent before sending non-essential messages. WhatsApp opt-in is especially important for academy reminders and campaigns.</p>{message && <p className="mt-6 rounded-lg border border-amber-700/50 bg-amber-950/40 p-4 text-sm text-amber-100">{message}</p>}{saveConfirmation && <p className="mt-6 rounded-lg border border-emerald-700/50 bg-emerald-950/40 p-4 text-sm text-emerald-100">✓ {saveConfirmation}</p>}<form onSubmit={save} className="mt-8 rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="grid gap-3 sm:grid-cols-2"><select value={recipientType} onChange={e => { setRecipientType(e.target.value); setRecipientId(""); setSaveConfirmation(""); }} className={field}><option>Guardian</option><option>Student</option></select><select value={recipientId} onChange={e => { setRecipientId(e.target.value); setSaveConfirmation(""); }} className={field}><option value="">Select a {recipientType.toLowerCase()}</option>{people.map(person => <option key={person.id} value={person.id}>{person.firstName} {person.lastName}{person.email ? ` · ${person.email}` : ""}{person.phone ? ` · ${person.phone}` : ""}</option>)}</select></div>{recipientId && <div className="mt-6 grid gap-4 rounded-lg border border-slate-700 bg-slate-950 p-5"><label className="flex gap-3 text-slate-200"><input type="checkbox" checked={emailAllowed} onChange={e => setEmailAllowed(e.target.checked)} /> Email consent recorded</label><label className="flex gap-3 text-slate-200"><input type="checkbox" checked={whatsAppAllowed} onChange={e => setWhatsAppAllowed(e.target.checked)} /> WhatsApp consent recorded</label><label className="flex gap-3 text-slate-200"><input type="checkbox" checked={marketingAllowed} onChange={e => setMarketingAllowed(e.target.checked)} /> Marketing/promotional messages allowed</label><textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="How and when was consent collected? (optional)" className={`${field} min-h-24`} /></div>}<button disabled={!academy || !recipientId} className="mt-5 rounded-lg bg-cyan-400 px-5 py-2.5 font-semibold text-slate-950 disabled:opacity-60">Save preferences</button></form></div></main>; }
