"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { academyApi, apiHeaders } from "@/lib/api";

type Academy = { id: string; name: string }; type Course = { id: string; name: string; academyType: string }; type Batch = { id: string; name: string; courseId: string; capacity: number; startDate?: string | null; endDate?: string | null };

export default function BatchesPage() {
  const [academies, setAcademies] = useState<Academy[]>([]); const [academyId, setAcademyId] = useState(""); const [courses, setCourses] = useState<Course[]>([]); const [batches, setBatches] = useState<Batch[]>([]); const [courseId, setCourseId] = useState(""); const [name, setName] = useState(""); const [capacity, setCapacity] = useState("10"); const [message, setMessage] = useState("");
  async function loadAcademies() { const r = await academyApi("/api/academies", { cache: "no-store" }); if (!r.ok) throw new Error(); const d: Academy[] = await r.json(); setAcademies(d); if (!academyId && d.length) setAcademyId(d[0].id); }
  async function loadCourses(id: string) { if (!id) return setCourses([]); const r = await academyApi(`/api/academies/${id}/courses`, { cache: "no-store" }); if (!r.ok) throw new Error(); const d: Course[] = await r.json(); setCourses(d); if (!courseId && d.length) setCourseId(d[0].id); }
  async function loadBatches(id: string) { if (!id) return setBatches([]); const r = await academyApi(`/api/academies/${id}/batches`, { cache: "no-store" }); if (!r.ok) throw new Error(); setBatches(await r.json()); }
  useEffect(() => { void loadAcademies().catch(() => setMessage("The AcademyDesk API is not reachable.")); }, []); useEffect(() => { void loadCourses(academyId).catch(() => setMessage("Courses could not be loaded.")); void loadBatches(academyId).catch(() => setMessage("Batches could not be loaded.")); }, [academyId]);
  async function createBatch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const r = await academyApi(`/api/academies/${academyId}/batches`, { method: "POST", headers: apiHeaders(true), body: JSON.stringify({ name, courseId, capacity: Number(capacity) }) }); if (!r.ok) return setMessage("The batch could not be saved."); setName(""); setMessage(""); await loadBatches(academyId); }
  return <main className="min-h-screen bg-slate-950 px-6 py-12 text-slate-100"><div className="mx-auto max-w-5xl"><Link href="/" className="text-sm text-cyan-300">← Academy setup</Link><h1 className="mt-4 text-4xl font-semibold">Batches and classes</h1><p className="mt-3 text-slate-300">Turn courses into scheduled groups ready for enrolment.</p>{message && <p className="mt-5 rounded-lg border border-amber-700/50 bg-amber-950/40 p-3 text-sm text-amber-200">{message}</p>}{academies.length === 0 ? <p className="mt-8 rounded-lg border border-dashed border-slate-700 p-8 text-center text-slate-400">Create an academy and course first.</p> : <><label className="mt-8 block text-sm text-slate-300" htmlFor="academy">Academy</label><select id="academy" value={academyId} onChange={(e) => setAcademyId(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2">{academies.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><section className="mt-6 grid gap-6 md:grid-cols-2"><form onSubmit={createBatch} className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Add batch</h2><select value={courseId} onChange={(e) => setCourseId(e.target.value)} className="mt-5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" required><option value="">Select course</option>{courses.map((c) => <option key={c.id} value={c.id}>{c.name} · {c.academyType}</option>)}</select><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Batch name" className="mt-3 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" required /><input type="number" min="1" max="1000" value={capacity} onChange={(e) => setCapacity(e.target.value)} placeholder="Capacity" className="mt-3 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2" required /><button className="mt-5 w-full rounded-lg bg-cyan-400 px-4 py-2.5 font-semibold text-slate-950 hover:bg-cyan-300">Create batch</button></form><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Active batches</h2>{batches.length === 0 ? <p className="mt-6 text-slate-400">No batches yet.</p> : <ul className="mt-4 space-y-3">{batches.map((b) => <li key={b.id} className="rounded-lg border border-slate-700 p-4"><div className="font-medium">{b.name}</div><div className="mt-1 text-sm text-slate-400">Capacity: {b.capacity}</div></li>)}</ul>}</section></section></>}</div></main>;
}
