"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { academyApi } from "@/lib/api";

type Academy = { id: string };
type ImportRow = { firstName: string; lastName: string; studentNumber: string | null; email: string | null; phone: string | null; admissionDate: null };
const exports = [["students", "Student register"], ["guardians", "Guardian register"], ["enrollments", "Enrolment register"], ["invoices", "Invoice ledger"], ["payments", "Payment reconciliation ledger"]] as const;

export default function DataOperations() {
  const [academy, setAcademy] = useState<Academy>(); const [message, setMessage] = useState("Loading data operations…"); const [rows, setRows] = useState<ImportRow[]>([]); const [fileName, setFileName] = useState(""); const [validating, setValidating] = useState(false); const [importing, setImporting] = useState(false);
  useEffect(() => { void academyApi("/api/academies").then(async response => { if (!response.ok) throw Error(); const academies: Academy[] = await response.json(); setAcademy(academies[0]); setMessage(academies[0] ? "" : "No academy found."); }).catch(() => setMessage("Data operations could not be loaded.")); }, []);
  async function download(resource: string) { if (!academy) return; const response = await academyApi(`/api/academies/${academy.id}/exports/${resource}`); if (!response.ok) return setMessage("Export could not be generated."); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `academydesk-${resource}.csv`; link.click(); URL.revokeObjectURL(url); setMessage("Export downloaded."); }
  async function loadCsv(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const text = await file.text(); const [head, ...lines] = text.trim().split(/\r?\n/); const headers = head.split(",").map(value => value.trim()); setRows(lines.filter(Boolean).map(line => { const values = line.split(",").map(value => value.trim()); return { firstName: values[headers.indexOf("FirstName")] || "", lastName: values[headers.indexOf("LastName")] || "", studentNumber: values[headers.indexOf("StudentNumber")] || null, email: values[headers.indexOf("Email")] || null, phone: values[headers.indexOf("Phone")] || null, admissionDate: null }; })); setFileName(file.name); setMessage("CSV loaded. Validate it before importing."); }
  async function validate() { if (!academy || !rows.length) return; setValidating(true); try { const response = await academyApi(`/api/academies/${academy.id}/imports/students/validate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows }) }); const result = await response.json(); setMessage(result.errors?.length ? `${result.errors.length} validation errors: ${result.errors.map((error: { row: string; message: string }) => `row ${error.row} ${error.message}`).join("; ")}` : "Validation passed. Ready to import."); } finally { setValidating(false); } }
  async function importRows() { if (!academy || !rows.length) return; setImporting(true); try { const response = await academyApi(`/api/academies/${academy.id}/imports/students`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows }) }); const result = await response.json(); setMessage(response.ok ? `${result.imported} students imported.` : result.message || "Import failed."); if (response.ok) { setRows([]); setFileName(""); } } finally { setImporting(false); } }
  return <main className="enterprise-settings data-operations-standard"><header className="data-operations-heading"><span className="data-operations-icon" aria-hidden="true">⇄</span><div><p>Administration</p><h1>Data operations centre</h1></div></header>{message && <p className="data-operations-notice" role="status">{message}</p>}<section className="data-operations-kpis"><article><span>Export registers</span><b>{exports.length}</b><small>Download controlled academy data sets.</small></article><article><span>Import rows loaded</span><b>{rows.length}</b><small>{fileName || "No student CSV selected."}</small></article><article><span>Import safeguard</span><b>Validate</b><small>Validation is required before importing.</small></article></section><section className="data-export-panel"><header><div><p>Data exports</p><h2>Academy registers</h2><small>Download current CSV copies for analysis, audit, or a controlled migration.</small></div></header><div className="data-export-grid">{exports.map(([resource, title]) => <article key={resource}><span aria-hidden="true">↓</span><h3>{title}</h3><p>CSV export</p><button onClick={() => void download(resource)} disabled={!academy} className="enterprise-action-button enterprise-action-button-secondary">Download CSV</button></article>)}</div></section><section className="data-import-panel"><header><div><p>Student import</p><h2>Validate &amp; import students</h2><small>Expected headers: FirstName, LastName, StudentNumber, Email, Phone.</small></div></header><div className="data-import-body"><label className="data-file-field"><span>Student CSV</span><input type="file" accept=".csv" onChange={event => void loadCsv(event)} /><b>{fileName || "Choose a CSV file"}</b></label>{rows.length > 0 && <div className="data-import-summary"><b>{rows.length} rows ready for validation</b><small>Review the result before running the final import.</small></div>}<div className="data-import-actions"><button onClick={() => void validate()} disabled={!rows.length || validating} className="enterprise-action-button enterprise-action-button-secondary">{validating ? "Validating…" : "Validate CSV"}</button><button onClick={() => void importRows()} disabled={!rows.length || importing} className="enterprise-action-button">{importing ? "Importing…" : "Import validated rows"}</button></div></div></section></main>;
}
