"use client";

import { FormEvent, useEffect, useState } from "react";
import { academyApi, apiHeaders } from "@/lib/api";

type Academy = { id: string }; type Lead = { id: string; fullName: string; programInterest?: string | null }; type Batch = { id: string; name: string }; type Teacher = { id: string; firstName: string; lastName: string }; type Trial = { id: string; leadId: string; batchId?: string | null; teacherId?: string | null; scheduledAtUtc: string; status: string; notes?: string | null };
const trialStatuses = ["Booked", "Completed", "Cancelled", "NoShow"];

export default function TrialBookingsPage() {
  const [academy, setAcademy] = useState<Academy>(); const [leads, setLeads] = useState<Lead[]>([]); const [batches, setBatches] = useState<Batch[]>([]); const [teachers, setTeachers] = useState<Teacher[]>([]); const [trials, setTrials] = useState<Trial[]>([]); const [message, setMessage] = useState("Loading trial bookings…");
  const [leadId, setLeadId] = useState(""); const [batchId, setBatchId] = useState(""); const [teacherId, setTeacherId] = useState(""); const [scheduledAt, setScheduledAt] = useState(""); const [notes, setNotes] = useState("");
  async function load(academyId?: string) { const id = academyId ?? academy?.id; if (!id) return; const [leadResponse, batchResponse, teacherResponse, trialResponse] = await Promise.all([academyApi(`/api/academies/${id}/leads`), academyApi(`/api/academies/${id}/batches`), academyApi(`/api/academies/${id}/teachers`), academyApi(`/api/academies/${id}/sales-marketing/trials`)]); if (![leadResponse, batchResponse, teacherResponse, trialResponse].every((response) => response.ok)) throw new Error(); setLeads(await leadResponse.json()); setBatches(await batchResponse.json()); setTeachers(await teacherResponse.json()); setTrials(await trialResponse.json()); setMessage(""); }
  useEffect(() => { void (async () => { try { const response = await academyApi("/api/academies"); const academies: Academy[] = await response.json(); if (!response.ok || !academies[0]) throw new Error(); setAcademy(academies[0]); await load(academies[0].id); } catch { setMessage("Trial bookings could not be loaded. Please sign in and restart the API if needed."); } })(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!academy) return; const response = await academyApi(`/api/academies/${academy.id}/sales-marketing/trials`, { method: "POST", headers: apiHeaders(true), body: JSON.stringify({ leadId, batchId: batchId || null, teacherId: teacherId || null, scheduledAtUtc: new Date(scheduledAt).toISOString(), notes: notes || null }) }); if (!response.ok) return setMessage("Select a lead and a valid time for the trial."); setLeadId(""); setBatchId(""); setTeacherId(""); setScheduledAt(""); setNotes(""); await load(); }
  async function update(trial: Trial, status: string) { if (!academy) return; const response = await academyApi(`/api/academies/${academy.id}/sales-marketing/trials/${trial.id}/status`, { method: "PATCH", headers: apiHeaders(true), body: JSON.stringify({ status }) }); if (!response.ok) return setMessage("Trial status could not be updated."); await load(); }
  const leadName = (id: string) => leads.find((lead) => lead.id === id)?.fullName ?? "Lead"; const batchName = (id?: string | null) => batches.find((batch) => batch.id === id)?.name ?? "No class or batch"; const teacherName = (id?: string | null) => { const teacher = teachers.find((item) => item.id === id); return teacher ? `${teacher.firstName} ${teacher.lastName}` : "Unassigned"; };
  return <main className="enterprise-settings"><header className="enterprise-page-header"><p>Sales & Marketing</p><h2>Trial-class bookings</h2></header><p className="enterprise-page-intro">Book a lead’s trial class, assign the right teacher, and record the result.</p>{message && <p className="mt-5 text-sm text-amber-500">{message}</p>}<section className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={create} className="surface-panel rounded-xl p-5"><h3 className="font-semibold">Book trial class</h3><select required value={leadId} onChange={(event) => setLeadId(event.target.value)} className="mt-4 w-full"><option value="">Select lead</option>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.fullName}{lead.programInterest ? ` · ${lead.programInterest}` : ""}</option>)}</select><div className="mt-3 grid gap-3 sm:grid-cols-2"><select value={batchId} onChange={(event) => setBatchId(event.target.value)}><option value="">No class or batch</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{batch.name}</option>)}</select><select value={teacherId} onChange={(event) => setTeacherId(event.target.value)}><option value="">No teacher assigned</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.firstName} {teacher.lastName}</option>)}</select></div><input required type="datetime-local" value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} className="mt-3 w-full" /><textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Notes for the trial" className="mt-3 min-h-24 w-full" /><button className="primary-action mt-5" disabled={!academy}>Book trial class</button></form><section className="space-y-3">{trials.length === 0 ? <div className="surface-panel rounded-xl p-5 text-sm text-slate-500">No trial classes booked yet.</div> : trials.map((trial) => <article key={trial.id} className="surface-panel flex flex-wrap items-center justify-between gap-4 rounded-xl p-5"><div><h3 className="font-semibold">{leadName(trial.leadId)}</h3><p className="mt-1 text-sm text-slate-500">{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" }).format(new Date(trial.scheduledAtUtc))} IST · {batchName(trial.batchId)} · {teacherName(trial.teacherId)}</p>{trial.notes && <p className="mt-2 text-sm text-slate-500">{trial.notes}</p>}</div><select value={trial.status} onChange={(event) => void update(trial, event.target.value)} className="min-w-32">{trialStatuses.map((item) => <option key={item}>{item}</option>)}</select></article>)}</section></section></main>;
}
