"use client";

import { useEffect, useState } from "react";
import { academyApi, apiHeaders } from "@/lib/api";

type Academy = { id: string };
type Settings = { taxRegistrationNumber: string; taxLabel: string; taxRatePercent: number; defaultPaymentTermsDays: number; taxInclusivePricing: boolean; invoiceLogoUrl?: string; invoiceAuthorityName?: string; invoiceAuthorityTitle?: string; invoiceSignatureUrl?: string; invoiceTemplateKey: string };

export default function FinancePolicy() {
  const [academy, setAcademy] = useState<Academy>();
  const [settings, setSettings] = useState<Settings>();
  const [message, setMessage] = useState("Loading finance policy…");
  useEffect(() => { void (async () => { try { const academies: Academy[] = await (await academyApi("/api/academies")).json(); if (!academies[0]) throw Error(); setAcademy(academies[0]); setSettings(await (await academyApi(`/api/academies/${academies[0].id}/finance-governance/settings`)).json()); setMessage(""); } catch { setMessage("Finance policy could not be loaded."); } })(); }, []);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!academy) return; const form = new FormData(event.currentTarget); const response = await academyApi(`/api/academies/${academy.id}/finance-governance/settings`, { method: "PUT", headers: apiHeaders(true), body: JSON.stringify({ taxRegistrationNumber: form.get("taxRegistrationNumber"), taxLabel: form.get("taxLabel"), taxRatePercent: Number(form.get("taxRatePercent")), defaultPaymentTermsDays: Number(form.get("defaultPaymentTermsDays")), taxInclusivePricing: form.get("taxInclusivePricing") === "on", invoiceLogoUrl: form.get("invoiceLogoUrl"), invoiceAuthorityName: form.get("invoiceAuthorityName"), invoiceAuthorityTitle: form.get("invoiceAuthorityTitle"), invoiceSignatureUrl: form.get("invoiceSignatureUrl"), invoiceTemplateKey: form.get("invoiceTemplateKey") }) }); if (!response.ok) return setMessage("Finance policy could not be saved."); setSettings(await response.json()); setMessage("Finance policy saved."); }
  return <main className="enterprise-settings finance-module"><header className="enterprise-page-header"><p>Finance / policy</p><h2>Tax and payment policy</h2><span>Set tax rules and branded invoice details used when printing or saving as PDF.</span></header>{message && <p className="enterprise-settings-empty mt-5">{message}</p>}{settings && <form onSubmit={save} className="surface-panel mt-5 max-w-3xl rounded-xl p-5"><h3>Invoice defaults</h3><div className="mt-4 grid gap-3"><input name="taxRegistrationNumber" defaultValue={settings.taxRegistrationNumber} className="field" placeholder="GST registration number"/><input name="taxLabel" defaultValue={settings.taxLabel} className="field" placeholder="Tax label"/><div className="grid gap-3 md:grid-cols-2"><label className="field-label">Tax rate (%)<input name="taxRatePercent" type="number" step="0.01" defaultValue={settings.taxRatePercent} className="field"/></label><label className="field-label">Default payment terms (days)<input name="defaultPaymentTermsDays" type="number" defaultValue={settings.defaultPaymentTermsDays} className="field"/></label></div><label className="consent-check"><input name="taxInclusivePricing" type="checkbox" defaultChecked={settings.taxInclusivePricing}/> Tax-inclusive pricing</label></div><h3 className="mt-7">Invoice branding and authority</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="field-label md:col-span-2">Academy logo URL<input name="invoiceLogoUrl" type="url" defaultValue={settings.invoiceLogoUrl ?? ""} className="field" placeholder="https://…/academy-logo.png"/></label><label className="field-label">Authorised signatory name<input name="invoiceAuthorityName" defaultValue={settings.invoiceAuthorityName ?? ""} className="field" placeholder="e.g. Kavya Sharma"/></label><label className="field-label">Designation<input name="invoiceAuthorityTitle" defaultValue={settings.invoiceAuthorityTitle ?? ""} className="field" placeholder="e.g. Finance Manager"/></label><label className="field-label">Signature image URL<input name="invoiceSignatureUrl" type="url" defaultValue={settings.invoiceSignatureUrl ?? ""} className="field" placeholder="https://…/signature.png"/></label><label className="field-label">Invoice theme<select name="invoiceTemplateKey" defaultValue={settings.invoiceTemplateKey || "Classic"} className="field"><option>Classic</option><option>Modern</option><option>Minimal</option><option>Formal</option></select></label></div><button className="enterprise-action-button mt-5">Save invoice settings</button></form>}</main>;
}
